'use client';

import { useCallback,useState } from 'react';import type{ReactElement}from'react';import{motion,AnimatePresence}from'framer-motion';import{IconBolt,IconBrain,IconBroom,IconPackage,IconPencil,IconRefresh,IconScissors,IconShield,IconSparkle}from'./icons';import{errorMessage,extractCode,requestCodeHubAI}from'./codehub-ai-client';
interface AIRefactorPanelProps{code:string;language:string;onApply:(refactoredCode:string)=>void}
type RefactorAction='extract-function'|'rename-variable'|'simplify'|'add-error-handling'|'convert-async'|'split-component'|'add-memoization';
const REFACTOR_ACTIONS:{id:RefactorAction;label:string;Icon:(props:{size?:number})=>ReactElement;description:string}[]=[{id:'extract-function',label:'Extract Function',Icon:IconPackage,description:'Extract selected code into a reusable function'},{id:'rename-variable',label:'Smart Rename',Icon:IconPencil,description:'Suggest better variable/function names'},{id:'simplify',label:'Simplify Logic',Icon:IconBroom,description:'Reduce complexity and remove redundancy'},{id:'add-error-handling',label:'Add Error Handling',Icon:IconShield,description:'Add appropriate typed error handling'},{id:'convert-async',label:'Convert to Async',Icon:IconBolt,description:'Convert callbacks/promises to async/await'},{id:'split-component',label:'Split Component',Icon:IconScissors,description:'Break large component into smaller ones'},{id:'add-memoization',label:'Add Memoization',Icon:IconBrain,description:'Add memoization only where beneficial'}];
export function AIRefactorPanel({code,language,onApply}:AIRefactorPanelProps){const[isOpen,setIsOpen]=useState(false);const[selectedAction,setSelectedAction]=useState<RefactorAction|null>(null);const[result,setResult]=useState<string|null>(null);const[isProcessing,setIsProcessing]=useState(false);const[error,setError]=useState<string|null>(null);
const handleRefactor=useCallback(async(action:RefactorAction)=>{if(!code.trim())return;setSelectedAction(action);setIsProcessing(true);setResult(null);setError(null);try{const response=await requestCodeHubAI(`Refactor this ${language} code using the requested operation: ${action}. Preserve public behavior and types, do not add placeholder TODOs, and return only the complete refactored code in one fenced block.\n\n${code}`);setResult(extractCode(response));}catch(cause){setError(errorMessage(cause));}finally{setIsProcessing(false);}},[code,language]);
return <div className="ai-refactor"><button type="button" className="ai-refactor-trigger inline-flex items-center gap-1.5" onClick={()=>setIsOpen(v=>!v)}><IconRefresh size={12}/>Refactor</button><AnimatePresence>{isOpen&&<motion.div className="ai-refactor-panel" initial={{opacity:0,height:0}} animate={{opacity:1,height:'auto'}} exit={{opacity:0,height:0}}><div className="refactor-actions">{REFACTOR_ACTIONS.map(action=><button key={action.id} type="button" className={`refactor-action ${selectedAction===action.id?'is-active':''}`} onClick={()=>handleRefactor(action.id)} disabled={isProcessing||!code.trim()}><span className="refactor-icon inline-flex"><action.Icon size={15}/></span><div><strong>{action.label}</strong><p>{action.description}</p></div></button>)}</div>{isProcessing&&<div className="refactor-loading inline-flex items-center gap-1.5"><IconSparkle size={12}/>Analyzing code structure...</div>}{error&&<p className="text-xs text-rose-400" role="alert">{error}</p>}{result&&!isProcessing&&<div className="refactor-result"><header><span>Refactored code</span><button type="button" onClick={()=>onApply(result)}>Apply</button></header><pre><code>{result.slice(0,400)}{result.length>400?'\n...':''}</code></pre></div>}</motion.div>}</AnimatePresence></div>}
