import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, it, expect } from 'vitest';
import { generateTokensCssFile } from '../index';

/**
 * Drift guard for the committed `generated/quant-tokens.css` (spec §6.2).
 *
 * The stylesheet is produced by `pnpm --filter @quant/brand generate:tokens`
 * (which runs `scripts/generate-tokens-css.ts`) and committed to the repo so
 * apps can `@import '@quant/brand/generated/quant-tokens.css'` without a build
 * step. This test fails if someone edits the source tokens (or the generators) but forgets
 * to regenerate — or hand-edits the output — keeping the committed file and the
 * `@quant/brand` source of truth exactly in sync.
 */
describe('generated/quant-tokens.css', () => {
  const cssPath = fileURLToPath(new URL('../../generated/quant-tokens.css', import.meta.url));
  // Normalize CRLF so the guard is stable regardless of git autocrlf checkout.
  const committed = readFileSync(cssPath, 'utf8').replace(/\r\n/g, '\n');

  it('carries the DO-NOT-EDIT provenance header', () => {
    expect(committed).toContain('AUTO-GENERATED by @quant/brand');
  });

  it('is byte-for-byte the current generator output (regenerate if this fails)', () => {
    // Exact equality — NOT `toContain` — so CSS prepended or appended to the
    // committed file (a hand-edit, or a stale block left behind by a token change)
    // fails the guard too, not just a missing substring.
    expect(committed).toBe(generateTokensCssFile());
  });

  it('is the base (appless) document — no dangling per-app accent or alias', () => {
    expect(committed).not.toContain('--quant-app-color:');
    expect(committed).not.toContain('--app-color:');
  });
});
