// ============================================================================
// Database Schema - Media (QuantTube, QuantNeon, QuantEdits)
// ============================================================================

/** Video schema (QuantTube) */
export interface VideoSchema {
  id: string;
  userId: string;
  channelId: string;
  title: string;
  description: string;
  videoUrl: string;
  thumbnailUrl: string;
  previewUrl: string | null;
  duration: number;
  width: number;
  height: number;
  fps: number;
  codec: string;
  bitrate: number;
  fileSize: number;
  category: string;
  tags: string[];
  visibility: 'public' | 'unlisted' | 'private' | 'scheduled';
  ageRestricted: boolean;
  viewCount: number;
  likeCount: number;
  dislikeCount: number;
  commentCount: number;
  shareCount: number;
  watchTimeSeconds: number;
  averageViewDuration: number;
  transcription: string | null;
  subtitles: SubtitleTrack[];
  chapters: VideoChapter[];
  qualityVersions: VideoQuality[];
  monetizationStatus: 'enabled' | 'disabled' | 'limited';
  aiModerationStatus: 'pending' | 'approved' | 'flagged' | 'removed';
  processingStatus: 'uploading' | 'processing' | 'ready' | 'failed';
  publishedAt: string | null;
  scheduledAt: string | null;
  createdAt: string;
  updatedAt: string;
  deletedAt: string | null;
}

/** Subtitle track */
export interface SubtitleTrack {
  language: string;
  url: string;
  isAutoGenerated: boolean;
}

/** Video chapter */
export interface VideoChapter {
  title: string;
  startTime: number;
  endTime: number;
}

/** Video quality version */
export interface VideoQuality {
  resolution: '360p' | '480p' | '720p' | '1080p' | '1440p' | '4k';
  url: string;
  bitrate: number;
  fileSize: number;
}

/** Channel schema (QuantTube) */
export interface ChannelSchema {
  id: string;
  userId: string;
  name: string;
  handle: string;
  description: string;
  avatarUrl: string | null;
  bannerUrl: string | null;
  subscriberCount: number;
  videoCount: number;
  totalViews: number;
  isVerified: boolean;
  isMonetized: boolean;
  category: string;
  links: { title: string; url: string }[];
  createdAt: string;
  updatedAt: string;
}

/** Music/Audio track schema */
export interface AudioTrackSchema {
  id: string;
  artistId: string;
  albumId: string | null;
  title: string;
  audioUrl: string;
  coverArtUrl: string | null;
  duration: number;
  genre: string;
  bpm: number | null;
  key: string | null;
  isExplicit: boolean;
  playCount: number;
  likeCount: number;
  lyrics: string | null;
  credits: AudioCredit[];
  isrc: string | null;
  createdAt: string;
  updatedAt: string;
}

/** Audio credit */
export interface AudioCredit {
  role: string;
  name: string;
  userId: string | null;
}

/** Album schema */
export interface AlbumSchema {
  id: string;
  artistId: string;
  title: string;
  coverArtUrl: string;
  description: string | null;
  type: 'album' | 'single' | 'ep' | 'compilation';
  genre: string;
  releaseDate: string;
  trackCount: number;
  totalDuration: number;
  createdAt: string;
  updatedAt: string;
}

/** Playlist schema */
export interface PlaylistSchema {
  id: string;
  userId: string;
  name: string;
  description: string | null;
  coverImageUrl: string | null;
  type: 'video' | 'music';
  visibility: 'public' | 'unlisted' | 'private';
  itemCount: number;
  totalDuration: number;
  followerCount: number;
  isCollaborative: boolean;
  createdAt: string;
  updatedAt: string;
}

/** Photo schema (QuantNeon) */
export interface PhotoSchema {
  id: string;
  userId: string;
  imageUrl: string;
  thumbnailUrl: string;
  originalUrl: string;
  width: number;
  height: number;
  fileSize: number;
  format: string;
  caption: string | null;
  altText: string | null;
  location: GeoLocation | null;
  tags: string[];
  peopleTagged: PeopleTag[];
  filters: AppliedFilter[];
  likeCount: number;
  commentCount: number;
  shareCount: number;
  saveCount: number;
  visibility: 'public' | 'followers' | 'close_friends' | 'private';
  aiLabels: string[];
  createdAt: string;
  updatedAt: string;
  deletedAt: string | null;
}

/** Geographic location */
export interface GeoLocation {
  latitude: number;
  longitude: number;
  name: string | null;
  address: string | null;
}

/** People tag on photo */
export interface PeopleTag {
  userId: string;
  x: number;
  y: number;
}

/** Applied filter data */
export interface AppliedFilter {
  name: string;
  intensity: number;
  parameters: Record<string, number>;
}

/** Editing project schema (QuantEdits) */
export interface EditingProjectSchema {
  id: string;
  userId: string;
  name: string;
  type: 'video' | 'photo' | 'audio';
  thumbnailUrl: string | null;
  sourceMediaUrls: string[];
  outputUrl: string | null;
  outputFormat: string;
  resolution: string;
  fps: number | null;
  duration: number | null;
  timeline: TimelineData;
  status: 'draft' | 'rendering' | 'completed' | 'failed';
  renderProgress: number;
  autoSaveEnabled: boolean;
  lastSavedAt: string;
  createdAt: string;
  updatedAt: string;
}

/** Timeline data for editor */
export interface TimelineData {
  tracks: TimelineTrack[];
  duration: number;
  resolution: { width: number; height: number };
}

/** Timeline track */
export interface TimelineTrack {
  id: string;
  type: 'video' | 'audio' | 'text' | 'effect' | 'image';
  clips: TimelineClip[];
  isMuted: boolean;
  isLocked: boolean;
  volume: number;
  opacity: number;
}

/** Timeline clip */
export interface TimelineClip {
  id: string;
  sourceUrl: string;
  startTime: number;
  endTime: number;
  inPoint: number;
  outPoint: number;
  effects: string[];
  transitions: string[];
}

/** Live stream schema */
export interface LiveStreamSchema {
  id: string;
  userId: string;
  channelId: string;
  title: string;
  description: string;
  thumbnailUrl: string | null;
  streamKey: string;
  rtmpUrl: string;
  hlsUrl: string | null;
  status: 'scheduled' | 'live' | 'ended' | 'failed';
  viewerCount: number;
  peakViewerCount: number;
  chatEnabled: boolean;
  donationsEnabled: boolean;
  category: string;
  tags: string[];
  startedAt: string | null;
  endedAt: string | null;
  scheduledAt: string | null;
  duration: number | null;
  recordingUrl: string | null;
  createdAt: string;
  updatedAt: string;
}

export const VIDEOS_TABLE = {
  tableName: 'videos',
  columns: [
    { name: 'id', type: 'UUID', primaryKey: true },
    { name: 'user_id', type: 'UUID', nullable: false, references: 'users(id)' },
    { name: 'channel_id', type: 'UUID', nullable: false, references: 'channels(id)' },
    { name: 'title', type: 'VARCHAR(200)', nullable: false },
    { name: 'description', type: 'TEXT', nullable: false },
    { name: 'video_url', type: 'TEXT', nullable: false },
    { name: 'thumbnail_url', type: 'TEXT', nullable: false },
    { name: 'duration', type: 'INTEGER', nullable: false },
    { name: 'category', type: 'VARCHAR(50)', nullable: false },
    { name: 'tags', type: "JSONB DEFAULT '[]'", nullable: false },
    { name: 'visibility', type: "VARCHAR(20) DEFAULT 'public'", nullable: false },
    { name: 'view_count', type: 'BIGINT DEFAULT 0', nullable: false },
    { name: 'like_count', type: 'BIGINT DEFAULT 0', nullable: false },
    { name: 'comment_count', type: 'BIGINT DEFAULT 0', nullable: false },
    { name: 'processing_status', type: "VARCHAR(20) DEFAULT 'uploading'", nullable: false },
    { name: 'published_at', type: 'TIMESTAMPTZ', nullable: true },
    { name: 'created_at', type: 'TIMESTAMPTZ DEFAULT NOW()', nullable: false },
    { name: 'updated_at', type: 'TIMESTAMPTZ DEFAULT NOW()', nullable: false },
    { name: 'deleted_at', type: 'TIMESTAMPTZ', nullable: true },
  ],
  indexes: [
    { name: 'idx_videos_user', columns: ['user_id'] },
    { name: 'idx_videos_channel', columns: ['channel_id'] },
    { name: 'idx_videos_category', columns: ['category'] },
    { name: 'idx_videos_trending', columns: ['view_count', 'published_at'] },
  ],
} as const;
