// ============================================================================
// QuantTube API - Subtitle Service
// Auto-caption generation, translation, SRT/VTT formats
// ============================================================================

interface SubtitleCue {
  id: string;
  startTime: number;
  endTime: number;
  text: string;
  speaker: string | null;
}

interface SubtitleTrack {
  id: string;
  videoId: string;
  language: string;
  languageCode: string;
  isDefault: boolean;
  isAutoGenerated: boolean;
  cues: SubtitleCue[];
  status: 'pending' | 'processing' | 'ready' | 'failed';
  createdAt: string;
  updatedAt: string;
}

interface TranslationRequest {
  trackId: string;
  targetLanguage: string;
  targetLanguageCode: string;
}

type SubtitleFormat = 'srt' | 'vtt' | 'json';

class SubtitleService {
  private tracks: Map<string, SubtitleTrack> = new Map();

  async generateAutoSubtitles(videoId: string, language: string = 'en'): Promise<SubtitleTrack> {
    const track: SubtitleTrack = {
      id: `sub_${Date.now()}_${Math.random().toString(36).substring(2, 8)}`,
      videoId,
      language: this.getLanguageName(language),
      languageCode: language,
      isDefault: true,
      isAutoGenerated: true,
      cues: [],
      status: 'processing',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    this.tracks.set(track.id, track);

    // Simulate async processing
    setTimeout(() => {
      const generatedCues = this.simulateTranscription(120);
      track.cues = generatedCues;
      track.status = 'ready';
      track.updatedAt = new Date().toISOString();
    }, 0);

    return track;
  }

  async getTracksForVideo(videoId: string): Promise<SubtitleTrack[]> {
    return Array.from(this.tracks.values()).filter(t => t.videoId === videoId);
  }

  async getTrack(trackId: string): Promise<SubtitleTrack | null> {
    return this.tracks.get(trackId) || null;
  }

  async updateCue(trackId: string, cueId: string, updates: Partial<SubtitleCue>): Promise<SubtitleCue | null> {
    const track = this.tracks.get(trackId);
    if (!track) return null;
    const cueIndex = track.cues.findIndex(c => c.id === cueId);
    if (cueIndex === -1) return null;
    track.cues[cueIndex] = { ...track.cues[cueIndex], ...updates };
    track.updatedAt = new Date().toISOString();
    return track.cues[cueIndex];
  }

  async addCue(trackId: string, cue: Omit<SubtitleCue, 'id'>): Promise<SubtitleCue> {
    const track = this.tracks.get(trackId);
    if (!track) throw new Error('Track not found');
    const newCue: SubtitleCue = { ...cue, id: `cue_${Date.now()}` };
    track.cues.push(newCue);
    track.cues.sort((a, b) => a.startTime - b.startTime);
    track.updatedAt = new Date().toISOString();
    return newCue;
  }

  async deleteCue(trackId: string, cueId: string): Promise<void> {
    const track = this.tracks.get(trackId);
    if (!track) throw new Error('Track not found');
    track.cues = track.cues.filter(c => c.id !== cueId);
    track.updatedAt = new Date().toISOString();
  }

  async translateTrack(request: TranslationRequest): Promise<SubtitleTrack> {
    const sourceTrack = this.tracks.get(request.trackId);
    if (!sourceTrack) throw new Error('Source track not found');

    const translatedTrack: SubtitleTrack = {
      id: `sub_${Date.now()}_${Math.random().toString(36).substring(2, 8)}`,
      videoId: sourceTrack.videoId,
      language: request.targetLanguage,
      languageCode: request.targetLanguageCode,
      isDefault: false,
      isAutoGenerated: true,
      cues: sourceTrack.cues.map(cue => ({
        ...cue,
        id: `cue_tr_${Date.now()}_${Math.random().toString(36).substring(2, 6)}`,
        text: `[${request.targetLanguageCode}] ${cue.text}`,
      })),
      status: 'ready',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    this.tracks.set(translatedTrack.id, translatedTrack);
    return translatedTrack;
  }

  async exportTrack(trackId: string, format: SubtitleFormat): Promise<string> {
    const track = this.tracks.get(trackId);
    if (!track) throw new Error('Track not found');

    switch (format) {
      case 'srt': return this.toSRT(track.cues);
      case 'vtt': return this.toVTT(track.cues);
      case 'json': return JSON.stringify(track.cues, null, 2);
      default: throw new Error(`Unsupported format: ${format}`);
    }
  }

  async importTrack(videoId: string, content: string, format: SubtitleFormat, language: string): Promise<SubtitleTrack> {
    let cues: SubtitleCue[];
    switch (format) {
      case 'srt': cues = this.parseSRT(content); break;
      case 'vtt': cues = this.parseVTT(content); break;
      case 'json': cues = JSON.parse(content); break;
      default: throw new Error(`Unsupported format: ${format}`);
    }

    const track: SubtitleTrack = {
      id: `sub_${Date.now()}_${Math.random().toString(36).substring(2, 8)}`,
      videoId,
      language: this.getLanguageName(language),
      languageCode: language,
      isDefault: false,
      isAutoGenerated: false,
      cues,
      status: 'ready',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    this.tracks.set(track.id, track);
    return track;
  }

  async deleteTrack(trackId: string): Promise<void> {
    this.tracks.delete(trackId);
  }

  private toSRT(cues: SubtitleCue[]): string {
    return cues.map((cue, idx) => {
      const start = this.formatSRTTime(cue.startTime);
      const end = this.formatSRTTime(cue.endTime);
      return `${idx + 1}\n${start} --> ${end}\n${cue.text}\n`;
    }).join('\n');
  }

  private toVTT(cues: SubtitleCue[]): string {
    const header = 'WEBVTT\n\n';
    const body = cues.map(cue => {
      const start = this.formatVTTTime(cue.startTime);
      const end = this.formatVTTTime(cue.endTime);
      return `${start} --> ${end}\n${cue.text}\n`;
    }).join('\n');
    return header + body;
  }

  private parseSRT(content: string): SubtitleCue[] {
    const blocks = content.trim().split(/\n\n+/);
    return blocks.map((block, idx) => {
      const lines = block.split('\n');
      return {
        id: `cue_import_${idx}`,
        startTime: 0,
        endTime: 5,
        text: lines.slice(2).join(' '),
        speaker: null,
      };
    });
  }

  private parseVTT(content: string): SubtitleCue[] {
    return this.parseSRT(content.replace(/^WEBVTT\n+/, ''));
  }

  private formatSRTTime(seconds: number): string {
    const h = Math.floor(seconds / 3600);
    const m = Math.floor((seconds % 3600) / 60);
    const s = Math.floor(seconds % 60);
    const ms = Math.floor((seconds % 1) * 1000);
    return `${h.toString().padStart(2, '0')}:${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')},${ms.toString().padStart(3, '0')}`;
  }

  private formatVTTTime(seconds: number): string {
    return this.formatSRTTime(seconds).replace(',', '.');
  }

  private getLanguageName(code: string): string {
    const names: Record<string, string> = { en: 'English', es: 'Spanish', fr: 'French', de: 'German', ja: 'Japanese', ko: 'Korean', pt: 'Portuguese', hi: 'Hindi', zh: 'Chinese', ar: 'Arabic' };
    return names[code] || code;
  }

  private simulateTranscription(durationSeconds: number): SubtitleCue[] {
    const cues: SubtitleCue[] = [];
    const phrases = ['Welcome to this video.', 'Today we will cover an important topic.', 'Let me explain the concept.', 'This is a key point to understand.', 'Now let us look at an example.', 'As you can see here.', 'This demonstrates the principle.', 'In conclusion.'];
    let time = 0;
    let idx = 0;
    while (time < durationSeconds) {
      const duration = 2 + Math.random() * 3;
      cues.push({
        id: `cue_auto_${idx}`,
        startTime: time,
        endTime: Math.min(time + duration, durationSeconds),
        text: phrases[idx % phrases.length],
        speaker: 'Speaker 1',
      });
      time += duration + 0.5;
      idx++;
    }
    return cues;
  }
}

export const subtitleService = new SubtitleService();
export default SubtitleService;
