name: quant_flutter_workspace
description: Root monorepo workspace for Quant Ecosystem Flutter multi-platform packages.
publish_to: 'none'

environment:
  sdk: '>=3.5.0 <4.0.0'

workspace:
  - quant_ui
  - quant_core
