// @vitest-environment jsdom
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { UniversalSSOTokenBridge } from '@quant/shared-ui';
import { persistSession, bootstrapSession, clearSession } from '../lib/auth-session';

describe('QuantChat SSO Token Handoff & Session Ingestion', () => {
  beforeEach(() => {
    localStorage.clear();
    clearSession();
    vi.restoreAllMocks();
  });

  afterEach(() => {
    localStorage.clear();
    clearSession();
  });

  it('persists SSO token across all ecosystem token keys and primes apiClient', () => {
    const testToken = 'jwt-token-chat-12345';
    const testRefresh = 'refresh-token-chat-67890';

    persistSession(testToken, testRefresh);

    expect(localStorage.getItem('quant_access_token')).toBe(testToken);
    expect(localStorage.getItem('quant_auth_token')).toBe(testToken);
    expect(localStorage.getItem('token')).toBe(testToken);
    expect(localStorage.getItem('quant_token')).toBe(testToken);
    expect(localStorage.getItem('quantchat_access_token')).toBe(testToken);
    expect(localStorage.getItem('quant_refresh_token')).toBe(testRefresh);

    // Bootstrap should succeed and hydrate apiClient
    const booted = bootstrapSession();
    expect(booted).toBe(true);
  });

  it('ingests __quant_sso_ticket generated by UniversalSSOTokenBridge', () => {
    const bridge = UniversalSSOTokenBridge.getInstance();

    const ticketPayload = {
      userId: 'user-chat-sso-1',
      email: 'alex@quantmail.in',
      displayName: 'Alex Rivers',
      token: 'jwt-alex-token-999',
    };

    bridge.setCurrentSession({
      ...ticketPayload,
      currentApp: 'quantchat',
    });

    const ticket = bridge.generateHandoffTicket('quantchat');
    expect(ticket).toBeTruthy();

    // Verify handoff ticket extraction
    const verified = bridge.verifyHandoffTicket(ticket!);
    expect(verified).not.toBeNull();
    expect(verified?.userId).toBe('user-chat-sso-1');
    expect(verified?.token).toBe('jwt-alex-token-999');

    // Ingest into quantchat session
    persistSession(verified!.token!, verified!.token!);
    expect(localStorage.getItem('quant_access_token')).toBe('jwt-alex-token-999');
  });

  it('clears all ecosystem keys on clearSession', () => {
    persistSession('token-to-clear', 'refresh-to-clear');
    clearSession();

    expect(localStorage.getItem('quant_access_token')).toBeNull();
    expect(localStorage.getItem('quant_auth_token')).toBeNull();
    expect(localStorage.getItem('token')).toBeNull();
    expect(localStorage.getItem('quant_token')).toBeNull();
    expect(localStorage.getItem('quantchat_access_token')).toBeNull();
    expect(localStorage.getItem('quant_refresh_token')).toBeNull();
  });
});
