// ============================================================================
// Data Pipeline Package - Barrel Export
// ============================================================================

export { EventStreamProcessor } from './core/event-stream-processor';
export { ETLPipeline } from './core/etl-pipeline';
export { DataValidator } from './core/data-validator';
export { DeadLetterQueue } from './core/dead-letter-queue';
export { BatchScheduler } from './core/batch-scheduler';
export { AggregationEngine } from './core/aggregation-engine';
export { WarehouseSchema } from './core/warehouse-schema';
export { MaterializedViewManager } from './core/materialized-views';
export { BehaviorAggregator } from './core/behavior-aggregator';
export { GrowthMetricsCalculator } from './core/growth-metrics';
export { RevenuePipeline } from './core/revenue-pipeline';

export type {
  Topic,
  Partition,
  ConsumerGroup,
  ConsumerGroupMember,
  PartitionAssignment,
  ConsumerGroupState,
  AssignmentStrategy,
  Offset,
  OffsetReset,
  Message,
  MessageBatch,
  SubscriptionHandler,
  ETLStageType,
  ETLStage,
  ExtractConfig,
  ExtractSource,
  TransformConfig,
  TransformOperation,
  TransformType,
  LoadConfig,
  LoadDestination,
  LoadMode,
  ConflictResolution,
  PipelineConfig,
  PipelineStatus,
  PipelineState,
  PipelineError,
  StageResult,
  StageMetrics,
  ValidationSchema,
  ValidationRule,
  ValidationRuleType,
  FieldValidator,
  FieldType,
  ValidationResult,
  ValidationErrorDetail,
  DeadLetterEntry,
  DeadLetterError,
  ErrorCategory,
  DLQEntryStatus,
  DLQConfig,
  RetryPolicy,
  BatchJob,
  CronSchedule,
  JobDependency,
  DependencyType,
  BatchConfig,
  JobStatus,
  JobRun,
  AggregationWindow,
  WindowType,
  AggregateFunction,
  AggregateFunctionType,
  WindowResult,
  FactTable,
  MeasureColumn,
  DimensionKey,
  DimensionTable,
  DimensionColumn,
  Hierarchy,
  SCDType,
  StarSchema,
  PartitionStrategy,
  PartitionType,
  IndexDefinition,
  SlowlyChangingDimension,
  MaterializedView,
  ViewRefreshPolicy,
  RefreshType,
  ViewDependency,
  ViewStatus,
  UserSession,
  SessionEvent,
  FunnelDefinition,
  FunnelStep,
  FunnelResult,
  FunnelStepResult,
  PathNode,
  PathTransition,
  GrowthMetrics,
  RetentionCohort,
  ChurnPrediction,
  ChurnFactor,
  ActiveUserMetrics,
  RevenueMetrics,
  MRRMovement,
  LTVEstimate,
  CACMetrics,
  QuickRatio,
} from './types';
