import type {
  Repo,
  FileNode,
  IssueItem,
  PRItem,
  DiscussionItem,
  WorkflowRunItem,
  ProjectCard,
  SecurityAlert,
  DeployedAgent,
} from './types';

// Initial Mock Repositories
export const INITIAL_REPOS: Repo[] = [
  {
    id: 'quant-ecosystem',
    name: 'Quant-Ecosystem',
    fullName: 'Quant-Ecosystem',
    description: 'Next-gen sovereign workspace, autonomous AI swarm, Git hub & Android client.',
    visibility: 'public',
    language: 'TypeScript',
    stars: 128,
    forks: 24,
    watching: 12,
    cloneUrl: 'https://quantmail.in/quantgit/Quant-Ecosystem.git',
    sshUrl: 'git@quantmail.in:Quant-Ecosystem.git',
    defaultBranch: 'main',
    latestCommit:
      'feat(quantgit): restore 4 bottom deck tabs, repos overview & publish android testing apk',
    latestCommitSha: 'ac612198',
    latestCommitTime: '1 hour ago',
    checksStatus: 'passing',
    license: 'MIT License',
    website: 'https://quantmail.in',
    topics: [
      'email',
      'sovereign-os',
      'agentic-ai',
      'git-smart-http',
      'monorepo',
      'jetpack-compose',
    ],
    branchCount: 348,
    commitCount: 2118,
    branches: ['main', 'feat/sprint-7-github-parity', 'fix/core-astra-audit', 'release/v1.0.0-apk'],
  },
  {
    id: 'quantmail-core',
    name: 'quantmail-core',
    fullName: 'quantmail-core',
    description:
      'Ultra-fast sovereign mail client with inline triage lenses & local ONNX semantic search.',
    visibility: 'private',
    language: 'TypeScript',
    stars: 42,
    forks: 5,
    watching: 8,
    cloneUrl: 'https://quantmail.in/quantgit/quantmail-core.git',
    sshUrl: 'git@quantmail.in:quantmail-core.git',
    defaultBranch: 'main',
    latestCommit: 'refactor(core): unify Bayesian spam classifier with isolated tenant indexes',
    latestCommitSha: '7f9104b2',
    latestCommitTime: '12 hours ago',
    checksStatus: 'passing',
    license: 'Proprietary',
    website: 'https://quantmail.in',
    topics: ['email', 'privacy', 'onnx', 'rust-worker'],
    branchCount: 42,
    commitCount: 846,
    branches: ['main', 'feat/offline-sync', 'fix/ses-deliverability'],
  },
  {
    id: 'quantchat-meet',
    name: 'quantchat-meet',
    fullName: 'quantchat-meet',
    description: 'LiveKit WebRTC gateway, SFU, voice AI agent, and calendar proactive alerts.',
    visibility: 'private',
    language: 'TypeScript',
    stars: 35,
    forks: 3,
    watching: 4,
    cloneUrl: 'https://quantmail.in/quantgit/quantchat-meet.git',
    sshUrl: 'git@quantmail.in:quantchat-meet.git',
    defaultBranch: 'main',
    latestCommit: 'feat(webrtc): LiveKit SFU cluster resilience and proactive voice call dispatch',
    latestCommitSha: '4fcec52e',
    latestCommitTime: 'yesterday',
    checksStatus: 'passing',
    license: 'Proprietary',
    website: 'https://quantmail.in',
    topics: ['webrtc', 'livekit', 'voice-ai', 'messaging'],
    branchCount: 28,
    commitCount: 512,
    branches: ['main', 'feat/livekit-sfu', 'feat/voice-bot'],
  },
  {
    id: 'quant-mobile-android',
    name: 'quant-mobile-android',
    fullName: 'quant-mobile-android',
    description:
      'Native Jetpack Compose Android client with hardware-accelerated WebView and offline resilience.',
    visibility: 'public',
    language: 'Kotlin',
    stars: 89,
    forks: 14,
    watching: 19,
    cloneUrl: 'https://quantmail.in/quantgit/quant-mobile-android.git',
    sshUrl: 'git@quantmail.in:quant-mobile-android.git',
    defaultBranch: 'main',
    latestCommit: 'release(android): Quant v1.0 universal APK build (targetSdk 36)',
    latestCommitSha: 'fa303afb',
    latestCommitTime: '2 hours ago',
    checksStatus: 'passing',
    license: 'Apache-2.0',
    website: 'https://quantmail.in',
    topics: ['android', 'kotlin', 'compose', 'apk', 'mobile'],
    branchCount: 16,
    commitCount: 394,
    branches: ['main', 'feat/jetpack-compose', 'fix/webview-perf'],
  },
];

// Mock File Tree Nodes
export const MOCK_FILES: FileNode[] = [
  {
    name: '.github',
    path: '.github',
    type: 'dir',
    lastCommit: 'ci: unified test matrix & gate sweep',
    lastCommitDate: '3 hours ago',
  },
  {
    name: 'android-project',
    path: 'android-project',
    type: 'dir',
    lastCommit: 'feat(mobile): native Jetpack Compose sovereign client',
    lastCommitDate: '1 hour ago',
  },
  {
    name: 'apk testing',
    path: 'apk testing',
    type: 'dir',
    lastCommit: 'release(android): Quant v1.0 universal APK build',
    lastCommitDate: '1 hour ago',
  },
  {
    name: 'apps',
    path: 'apps',
    type: 'dir',
    lastCommit: 'feat(quantmail): top command deck & 1:1 GitHub workspace',
    lastCommitDate: 'just now',
  },
  {
    name: 'backend',
    path: 'backend',
    type: 'dir',
    lastCommit: 'feat(collab): Yjs CRDT real-time persistence',
    lastCommitDate: 'yesterday',
  },
  {
    name: 'docs',
    path: 'docs',
    type: 'dir',
    lastCommit: 'docs(architecture): update 10 keeper apps ledger',
    lastCommitDate: '2 days ago',
  },
  {
    name: 'packages',
    path: 'packages',
    type: 'dir',
    lastCommit: 'refactor(shared-ui): fluid bubble intelligence without eyes',
    lastCommitDate: '2 hours ago',
  },
  {
    name: 'AGENT_MEMORY.md',
    path: 'AGENT_MEMORY.md',
    type: 'file',
    size: '98.5 KB',
    lastCommit: 'docs(memory): master agent memory & swarm ledger',
    lastCommitDate: '1 hour ago',
    content: `# 🧠 MASTER AGENT MEMORY & SWARM LEDGER\n\n> **CRITICAL SYSTEM DIRECTIVE**: This file is the single source of truth for all sessions and new chats. Antigravity MUST read this file before replying to any message, perform 50x self-critique against hallucination, verify features with live Chrome button clicks, orchestrate Notion Agents (Opus 5 / GPT-6 Astra) to do deep coding, and write back all updates immediately.\n\n## 🌟 1. PROJECT NORTH STAR\nQuant is one account that gives you email, chat, social, video, dating, creation tools, cloud storage, and a coding platform — all controllable by a single personal AI.\n\n## 👥 SWARM FLEET (8+ AGENTS)\n- CEO Astra (Command)\n- Dev 1: Auth & Security\n- Dev 2: Sentinel & QA\n- Dev 3: Calendar & Recurrence\n- Dev 4: QuantDrive & Storage\n- Dev 5: Workspaces & Collaboration\n- Dev 6: CodeHub & Git Infrastructure\n- Dev 7: QuantAI Swarm & Shared Memory`,
  },
  {
    name: 'TASK_PLANNER.md',
    path: 'TASK_PLANNER.md',
    type: 'file',
    size: '72.1 KB',
    lastCommit: 'chore(planner): update sprint milestones and live checkmarks',
    lastCommitDate: '1 hour ago',
    content: `# 📋 QUANT ECOSYSTEM — UNIFIED MASTER TASK PLANNER\n\n- [x] PR #260 (b68b86e4): Master Consolidation PR\n- [x] PR #247 (948e3612): QuantMail v2.0 Production Integration\n- [x] Task APK-01: Setup official Android CLI and SDK 36\n- [x] Task APK-02: Native Jetpack Compose sovereign client\n- [x] Task APK-03: Universal debug APK build (11.39 MB)\n- [x] Task APK-04: Distributed in 'apk testing/' on GitHub remote\n- [x] Task GIT-03: Restored 4 bottom deck tabs & repository overview`,
  },
  {
    name: 'package.json',
    path: 'package.json',
    type: 'file',
    size: '2.14 KB',
    lastCommit: 'chore: upgrade monorepo dependencies and strict TypeScript',
    lastCommitDate: '3 days ago',
    content: `{\n  "name": "quant-ecosystem",\n  "version": "1.0.0",\n  "private": true,\n  "scripts": {\n    "build": "turbo run build",\n    "dev": "turbo run dev",\n    "test": "turbo run test",\n    "lint": "turbo run lint",\n    "typecheck": "turbo run typecheck"\n  },\n  "devDependencies": {\n    "typescript": "^5.9.0",\n    "turbo": "^2.4.0",\n    "vitest": "^2.1.0"\n  }\n}`,
  },
  {
    name: 'pnpm-lock.yaml',
    path: 'pnpm-lock.yaml',
    type: 'file',
    size: '412 KB',
    lastCommit: 'chore: lockfile sync for shared-ui bubble avatar',
    lastCommitDate: '3 days ago',
    content: `lockfileVersion: '9.0'\n\nimporters:\n  .:\n    dependencies:\n      turbo: 2.4.0\n      typescript: 5.9.0`,
  },
  {
    name: 'README.md',
    path: 'README.md',
    type: 'file',
    size: '4.82 KB',
    lastCommit: 'docs: update ecosystem quickstart & architecture overview',
    lastCommitDate: 'last week',
    content: `# Quant Ecosystem — The Next NVIDIA of Software\n\nA unified sovereign operating ecosystem built for high-performance computing, intelligent mail triage, autonomous agentic development, and real git collaboration.\n\n\`\`\`bash\n# Clone the unified monorepo\ngit clone https://quantmail.in/quantgit/Quant-Ecosystem.git\n\n# Install dependencies and start development\npnpm install && pnpm dev\n\`\`\`\n\n## 📦 Features\n- **Flagship QuantMail**: Lightning-fast triage, local ONNX semantic search, offline drafts.\n- **QuantGit (CodeHub)**: 1:1 GitHub parity with Git Smart HTTP and real PR reviews.\n- **QuantChat & Meet**: WebRTC LiveKit meetings, voice AI assistants, proactive alarms.\n- **QuantDrive & Docs**: Multi-layer cloud storage, Yjs CRDT real-time document collaboration.\n- **Native Android Sovereign Shell**: Jetpack Compose + hardware-accelerated WebView client.`,
  },
];

// Initial Issues
export const INITIAL_ISSUES: IssueItem[] = [
  {
    id: 259,
    title: 'Fix QuantMail composer recipient tag overflow on small viewports',
    state: 'open',
    author: 'kundan',
    labels: [
      { name: 'bug', color: '#D73A4A' },
      { name: 'mobile', color: '#0E8A16' },
    ],
    commentsCount: 3,
    createdAt: '2 hours ago',
    body: 'On mobile viewports under 400px width, recipient pills in the email composer were wrapping awkwardly and causing horizontal layout overflow. Remediated via CSS flex-wrap and max-w-full containment.',
    assignee: 'Developer 6',
  },
  {
    id: 250,
    title: 'ADR-001: Consolidate Drive AI services & aggregate sum storage quota',
    state: 'open',
    author: 'astra-ceo',
    labels: [
      { name: 'architecture', color: '#1D76DB' },
      { name: 'storage', color: '#5319E7' },
    ],
    commentsCount: 8,
    createdAt: 'yesterday',
    body: 'Ported 5 Drive AI services (extract, summarize, search, duplicate, organize) into QuantMail Drive backend and replaced client-side quota calculation with single database aggregate sum query.',
    assignee: 'Developer 4',
  },
  {
    id: 138,
    title: 'CI Gate: Upgrade Vitest runner concurrency & memory pool clamps',
    state: 'open',
    author: 'sentinel',
    labels: [
      { name: 'ci/cd', color: '#FBCA04' },
      { name: 'performance', color: '#006B75' },
    ],
    commentsCount: 2,
    createdAt: '2 days ago',
    body: 'Increased Vitest worker pool to 4 isolated threads and added memory pool limit of 2048MB per worker to eliminate sporadic memory spikes during full-sweep CI runs.',
    assignee: 'Developer 2',
  },
  {
    id: 122,
    title: 'Zero-mock Yjs collaborative document branching and paragraph write-locks',
    state: 'open',
    author: 'forge',
    labels: [
      { name: 'docs', color: '#BFD4F2' },
      { name: 'crdt', color: '#D4C5F9' },
    ],
    commentsCount: 5,
    createdAt: '3 days ago',
    body: 'Implemented real CRDT document branching with 3-way Yjs merge and fine-grained paragraph permissions for multi-tenant enterprise editing.',
    assignee: 'Developer 5',
  },
  {
    id: 109,
    title: 'QuantChat LiveKit gateway WebRTC token refresh & background alarms',
    state: 'open',
    author: 'scout',
    labels: [
      { name: 'webrtc', color: '#E99695' },
      { name: 'realtime', color: '#0075CA' },
    ],
    commentsCount: 4,
    createdAt: '4 days ago',
    body: 'Added background keep-alive loop and automatic room token refresh before expiration during 60+ minute audio/video conferencing sessions.',
    assignee: 'Developer 7',
  },
];

// Initial Pull Requests
export const INITIAL_PRS: PRItem[] = [
  {
    id: 260,
    title: 'Master Consolidation PR (Waves B-F, Sprints 2-5, Wave F Deletions)',
    state: 'merged',
    author: 'astra-ceo',
    branchSource: 'feat/sprint-master-consolidation',
    branchTarget: 'main',
    checksStatus: 'passing',
    commentsCount: 14,
    createdAt: 'yesterday',
    body: 'Unified monorepo consolidation: pruned 7 dead standalone apps (-47,882 lines), integrated LiveKit WebRTC, Yjs CRDT docs, RRULE calendar recurrence, and 3-layer shared memory.',
    additions: 12450,
    deletions: 47882,
    changedFiles: 182,
  },
  {
    id: 257,
    title: 'feat(branding): Rebrand apps to @quant/quantwave, quantgram, and quantcooks',
    state: 'merged',
    author: 'pixel',
    branchSource: 'feat/app-rebranding',
    branchTarget: 'main',
    checksStatus: 'passing',
    commentsCount: 4,
    createdAt: '2 days ago',
    body: 'Cleaned up monorepo package identifiers and updated SSO permission scopes across all rebranded apps.',
    additions: 420,
    deletions: 310,
    changedFiles: 18,
  },
  {
    id: 261,
    title: 'feat(quantgit): 1:1 GitHub Full Functional Parity & Pixel-Perfect Dark UI/UX',
    state: 'open',
    author: 'Developer 6',
    branchSource: 'feat/quantgit-github-parity',
    branchTarget: 'main',
    checksStatus: 'passing',
    commentsCount: 6,
    createdAt: 'just now',
    body: 'Implemented complete 1:1 GitHub parity: all 10 tabs (Code, Issues, PRs, Agents, Discussions, Actions, Projects, Security, Insights, Settings), Two-column repository layout, line-numbered Blob Viewer, File Finder, Branch Switcher, Releases APK download drawer, and docked bottom deck.',
    additions: 2528,
    deletions: 646,
    changedFiles: 48,
  },
];

// Initial Discussions
export const INITIAL_DISCUSSIONS: DiscussionItem[] = [
  {
    id: 1,
    title: '📢 Quant Ecosystem v1.0 Staging Release & Android APK Distribution',
    category: 'Announcements',
    author: 'astra-ceo',
    upvotes: 42,
    commentsCount: 18,
    createdAt: '2 hours ago',
    body: 'We are thrilled to announce that Quant v1.0 Universal APK is officially compiled and downloadable directly from GitHub remote under apk testing/! Feedback welcome.',
  },
  {
    id: 2,
    title: '💡 RFC: Unified Credits Wallet ($1 = 1 Credit) & Creator Monetization',
    category: 'Ideas',
    author: 'ledger',
    upvotes: 29,
    commentsCount: 7,
    createdAt: 'yesterday',
    body: 'Proposing a unified credit model where creator earnings in QuantWave & QuantGram flow into a single wallet, redeemable via UPI and Stripe daily.',
  },
  {
    id: 3,
    title: '🙏 Best practices for configuring local ONNX runtime embeddings in QuantMail',
    category: 'Q&A',
    author: 'scout',
    upvotes: 19,
    commentsCount: 5,
    createdAt: '3 days ago',
    body: 'What is the optimal model size and quantization format (int8 vs fp16) for client-side web worker embeddings without burning laptop battery?',
  },
];

// Initial Actions Runs
export const INITIAL_ACTIONS: WorkflowRunItem[] = [
  {
    id: 34826613070,
    name: 'feat(quantgit): restore 4 bottom deck tabs, repos overview & publish …',
    workflow: 'Deploy staging (OIDC)',
    status: 'success',
    branch: 'main',
    event: 'workflow_dispatch',
    commitSha: 'ac612198',
    duration: '4m 55s',
    timeAgo: '15 minutes ago',
    jobs: [
      { name: 'Validate immutable main release', status: 'success', duration: '4s' },
      { name: 'Build and deploy quantmail', status: 'success', duration: '4m 51s' },
    ],
  },
  {
    id: 34826179762,
    name: 'feat(quantgit): restore 4 bottom deck tabs, repos overview & publish …',
    workflow: 'CI',
    status: 'success',
    branch: 'main',
    event: 'push',
    commitSha: 'ac612198',
    duration: '4m 18s',
    timeAgo: '25 minutes ago',
    jobs: [
      { name: 'gate', status: 'success', duration: '4m 18s' },
      { name: 'quantchat-coverage', status: 'success', duration: '1m 20s' },
      { name: 'memory-shadow-postgres', status: 'success', duration: '1m 45s' },
      { name: 'full-sweep', status: 'success', duration: '18m 20s' },
    ],
  },
  {
    id: 34826179781,
    name: 'feat(quantgit): restore 4 bottom deck tabs, repos overview & publish …',
    workflow: 'CodeQL Advanced',
    status: 'success',
    branch: 'main',
    event: 'push',
    commitSha: 'ac612198',
    duration: '3m 22s',
    timeAgo: '28 minutes ago',
    jobs: [
      { name: 'Analyze (javascript-typescript)', status: 'success', duration: '3m 10s' },
      { name: 'Analyze (python)', status: 'success', duration: '1m 05s' },
    ],
  },
];

// Initial Projects Kanban Cards
export const INITIAL_PROJECT_CARDS: ProjectCard[] = [
  {
    id: 'c1',
    title: 'Android APK Distribution on GitHub',
    column: 'done',
    tag: 'Mobile',
    assignee: 'Developer 6',
  },
  {
    id: 'c2',
    title: '1:1 GitHub Navigation & Two-Column Parity',
    column: 'done',
    tag: 'QuantGit',
    assignee: 'Pixel',
  },
  {
    id: 'c3',
    title: 'Line-Numbered File Blob Viewer & Copy Raw',
    column: 'done',
    tag: 'CodeHub',
    assignee: 'Forge',
  },
  {
    id: 'c4',
    title: 'Full 10-Tab Experience (Discussions, Projects, Security)',
    column: 'in_progress',
    tag: 'Core',
    assignee: 'Astra',
  },
  {
    id: 'c5',
    title: 'Real-time WebSocket Collaborative Terminal',
    column: 'todo',
    tag: 'QuantAI',
    assignee: 'Ledger',
  },
  {
    id: 'c6',
    title: 'Hardware YubiKey MFA Support in SSO',
    column: 'todo',
    tag: 'Auth',
    assignee: 'Developer 1',
  },
];

// Initial Security Alerts
export const INITIAL_SECURITY_ALERTS: SecurityAlert[] = [
  {
    id: 'sec-1',
    package: 'tar < 6.2.1',
    severity: 'moderate',
    cve: 'CVE-2024-37890',
    title: 'Arbitrary File Overwrite via symlink directory traversal',
    state: 'open',
  },
  {
    id: 'sec-2',
    package: 'micromatch < 4.0.8',
    severity: 'moderate',
    cve: 'CVE-2024-4067',
    title: 'Regular Expression Denial of Service (ReDoS) in glob parsing',
    state: 'open',
  },
  {
    id: 'sec-3',
    package: 'ws < 8.17.1',
    severity: 'low',
    cve: 'CVE-2024-37891',
    title: 'WebSocket payload framing timing side-channel',
    state: 'open',
  },
  {
    id: 'sec-4',
    package: 'braces < 3.0.3',
    severity: 'low',
    cve: 'CVE-2024-4068',
    title: 'Uncontrolled resource consumption in string expansion',
    state: 'open',
  },
];

// Swarm Fleet Catalog
export const AGENT_FLEET_CATALOG: DeployedAgent[] = [
  {
    id: 'astra',
    name: 'Astra',
    role: 'Executive Lead & Architecture Gatekeeper',
    pod: 'COMMAND',
    status: 'active',
    currentTask:
      'Enforcing 1:1 GitHub parity, two-column layout, and zero-hallucination verification.',
    initial: 'A',
    color: '#FF8C42',
    steps: [
      'Audited GitHub dark UI tokens',
      'Verified 10 repository tabs',
      'Confirmed live EKS staging build',
    ],
    thoughts:
      'All 10 tabs must have interactive functionality and reflect authentic GitHub dark theme (#0D1117).',
  },
  {
    id: 'sentinel',
    name: 'Sentinel',
    role: 'Audit & QA Sentinel',
    pod: 'SHIELD',
    status: 'analyzing',
    currentTask:
      'Continuous Vitest regression & CI gate surveillance across all monorepo packages.',
    initial: 'S',
    color: '#34D399',
    steps: [
      'Gate sweep passed in 4m18s',
      'Typecheck clean (zero emit errors)',
      'Zero console exceptions',
    ],
    thoughts: 'Watching test worker memory footprints and confirming zero unhandled exceptions.',
  },
  {
    id: 'forge',
    name: 'Forge',
    role: 'Fullstack Monorepo Engine',
    pod: 'ENGINE',
    status: 'building',
    currentTask:
      'Building 1:1 File Tree explorer with clickable blob viewer and breadcrumb navigation.',
    initial: 'F',
    color: '#60A5FA',
    steps: [
      'Parsed GitHub table layout',
      'Added line numbers to file viewer',
      'Wired branch selector modal',
    ],
    thoughts:
      'Developers expect to click on files and see line numbers, copy raw, and commit messages.',
  },
  {
    id: 'scout',
    name: 'Scout',
    role: 'Codebase Researcher',
    pod: 'RECON',
    status: 'idle',
    currentTask: 'Mapping competitor features from logged-in GitHub web sessions.',
    initial: 'R',
    color: '#A78BFA',
    steps: [
      'Inspected GitHub repo header',
      'Captured clone drawer protocol tabs',
      'Mapped Kanban project columns',
    ],
    thoughts:
      'GitHub puts Releases in the right sidebar with quick binary downloads. Quant APK must sit right there.',
  },
  {
    id: 'pixel',
    name: 'Pixel',
    role: 'UI/UX & Design Systems',
    pod: 'CANVAS',
    status: 'active',
    currentTask:
      'Polishing GitHub dark tokens (#0D1117, #010409, #30363D) and green buttons (#238636).',
    initial: 'P',
    color: '#F472B6',
    steps: [
      'Eliminated cartoon eyes from mascot',
      'Created authentic GitHub tabs with orange underline',
      'Added 2-column layout',
    ],
    thoughts:
      'The user wants real GitHub look and feel, not generic cards. Exact border colors make the difference.',
  },
  {
    id: 'ledger',
    name: 'Ledger',
    role: 'Database & Storage Migrations',
    pod: 'VAULT',
    status: 'idle',
    currentTask:
      'Managing repository tables, branches, issues, and pull requests in Prisma schema.',
    initial: 'L',
    color: '#FBBF24',
    steps: [
      'Schema 0058 verified',
      'Storage quota aggregate sum verified',
      'Prisma client generated',
    ],
    thoughts: 'All issue numbers and PR numbers must increment deterministically.',
  },
];
