// ============================================================================
// QuantTube - Type Definitions
// All types for video, music, shows, channels, live streaming
// ============================================================================

export interface Video {
  id: string;
  title: string;
  description: string;
  channelId: string;
  channelName: string;
  channelAvatar: string;
  thumbnailUrl: string;
  url: string;
  duration: number;
  views: number;
  likes: number;
  dislikes: number;
  commentCount: number;
  status: VideoStatus;
  type: VideoType;
  resolution: string;
  chapters: Chapter[];
  subtitles: Subtitle[];
  tags: string[];
  category: string;
  publishedAt: string;
  scheduledAt?: string;
}

export type VideoStatus = 'uploading' | 'processing' | 'published' | 'private' | 'unlisted' | 'scheduled';
export type VideoType = 'video' | 'short' | 'premiere';

export interface Chapter {
  id: string;
  title: string;
  startTime: number;
  endTime: number;
}

export interface Subtitle {
  id: string;
  language: string;
  label: string;
  url: string;
  isAutoGenerated: boolean;
}

export interface Track {
  id: string;
  title: string;
  artistId: string;
  artistName: string;
  albumId: string;
  albumName: string;
  albumCover: string;
  duration: number;
  trackNumber: number;
  streamUrl: string;
  genre: string;
  plays: number;
  explicit: boolean;
  releaseDate: string;
  lyrics?: SyncedLyric[];
}

export interface SyncedLyric {
  startTime: number;
  endTime: number;
  text: string;
  isChorus: boolean;
}

export interface Album {
  id: string;
  title: string;
  artistId: string;
  artistName: string;
  coverUrl: string;
  releaseDate: string;
  tracks: Track[];
  genre: string;
  type: 'album' | 'single' | 'ep';
  trackCount: number;
  totalDuration: number;
}

export interface Artist {
  id: string;
  name: string;
  bio: string;
  imageUrl: string;
  genres: string[];
  monthlyListeners: number;
  verified: boolean;
  topTracks: Track[];
  albums: Album[];
}

export interface Show {
  id: string;
  title: string;
  description: string;
  posterUrl: string;
  bannerUrl: string;
  genre: string[];
  rating: string;
  year: number;
  isOriginal: boolean;
  seasons: Season[];
  status: 'ongoing' | 'completed' | 'upcoming';
}

export interface Season {
  id: string;
  number: number;
  title: string;
  episodes: Episode[];
  releaseDate: string;
}

export interface Episode {
  id: string;
  number: number;
  title: string;
  description: string;
  duration: number;
  thumbnailUrl: string;
  streamUrl: string;
  releaseDate: string;
}

export interface Channel {
  id: string;
  name: string;
  handle: string;
  description: string;
  avatarUrl: string;
  bannerUrl: string;
  subscriberCount: number;
  videoCount: number;
  totalViews: number;
  verified: boolean;
  isSubscribed?: boolean;
  memberships: MembershipTier[];
}

export interface MembershipTier {
  id: string;
  name: string;
  price: number;
  perks: string[];
}

export interface Playlist {
  id: string;
  title: string;
  description: string;
  thumbnailUrl: string;
  ownerId: string;
  ownerName: string;
  type: 'video' | 'music' | 'mixed';
  visibility: 'public' | 'private' | 'unlisted';
  items: PlaylistItem[];
  itemCount: number;
  totalDuration: number;
  isCollaborative: boolean;
}

export interface PlaylistItem {
  id: string;
  contentId: string;
  contentType: 'video' | 'track' | 'episode';
  title: string;
  duration: number;
  position: number;
}

export interface LiveStream {
  id: string;
  channelId: string;
  channelName: string;
  title: string;
  thumbnailUrl: string;
  status: 'scheduled' | 'live' | 'ended';
  viewerCount: number;
  category: string;
  tags: string[];
  startedAt?: string;
  scheduledAt?: string;
}

export interface ChatMessage {
  id: string;
  streamId: string;
  userId: string;
  username: string;
  message: string;
  type: 'message' | 'superchat' | 'membership' | 'system';
  amount?: number;
  timestamp: string;
}

export interface WatchProgress {
  showId: string;
  episodeId: string;
  position: number;
  duration: number;
  completed: boolean;
  updatedAt: string;
}

export interface Recommendation {
  contentId: string;
  score: number;
  reason: string;
  contentType: string;
}

export interface SearchResult {
  id: string;
  type: 'video' | 'track' | 'album' | 'show' | 'channel' | 'playlist';
  title: string;
  description: string;
  thumbnailUrl: string;
  relevanceScore: number;
}

export interface PlayerState {
  currentContent: Video | Track | Episode | null;
  isPlaying: boolean;
  currentTime: number;
  duration: number;
  volume: number;
  muted: boolean;
  quality: string;
  playbackRate: number;
  isFullscreen: boolean;
  isMiniPlayer: boolean;
}

export interface QueueState {
  items: (Track | Video)[];
  currentIndex: number;
  shuffled: boolean;
  repeatMode: 'off' | 'one' | 'all';
}
