// Sovereign Quant Ecosystem - QuantChat Mock Repository & Initial State
// Strictly ZERO raw Unicode emojis throughout this file.

import 'package:flutter/material.dart';
import 'package:quant_core/quant_core.dart';
import 'package:quant_theme/quant_theme.dart';
import '../models/chat_models.dart';

class ChatMockData {
  ChatMockData._();

  static List<ChatConversation> getInitialConversations() {
    return [
      const ChatConversation(
        id: 'conv-1',
        contactId: 'usr-astra',
        name: 'CEO Astra (Notion AI Swarm)',
        avatarInitials: 'AS',
        avatarColor: QuantColors.moltenOrange,
        lastMessage: 'All 8 Notion agents dispatched. Tripartite Swarm operational.',
        lastMessageTime: '12:44',
        unreadCount: 3,
        isOnline: true,
        isTyping: true,
        isPinned: true,
        lastSeenText: 'Active in Swarm Control',
        lastMessageStatus: MessageDeliveryStatus.read,
      ),
      const ChatConversation(
        id: 'conv-2',
        contactId: 'usr-node-b',
        name: 'Node B (ChatGPT Agent OS Lead)',
        avatarInitials: 'NB',
        avatarColor: QuantColors.sovereignCyan,
        lastMessage: 'Track 2 live: Voice Orb 3D canvas and dynamic tool calling green.',
        lastMessageTime: '12:38',
        unreadCount: 1,
        isOnline: true,
        isTyping: false,
        isPinned: true,
        lastSeenText: 'Online (Node B Active)',
        lastMessageStatus: MessageDeliveryStatus.read,
      ),
      const ChatConversation(
        id: 'conv-3',
        contactId: 'usr-node-c',
        name: 'Node C (CLI Dev-Worker agy.exe)',
        avatarInitials: 'NC',
        avatarColor: QuantColors.obsidianPurple,
        lastMessage: 'PR #298 merged. Staging cluster running 20 pods smoothly.',
        lastMessageTime: '12:25',
        unreadCount: 0,
        isOnline: true,
        isTyping: false,
        isPinned: true,
        lastSeenText: 'Online (<12ms Staging)',
        lastMessageStatus: MessageDeliveryStatus.read,
      ),
      const ChatConversation(
        id: 'conv-4',
        contactId: 'usr-dev-1',
        name: 'Dev 1 (Auth & Security)',
        avatarInitials: 'D1',
        avatarColor: QuantColors.emeraldMatrix,
        lastMessage: 'Hardware Keystore signed prekey bundle validated successfully.',
        lastMessageTime: '11:52',
        unreadCount: 0,
        isOnline: true,
        isTyping: false,
        isPinned: false,
        lastSeenText: 'Online',
        lastMessageStatus: MessageDeliveryStatus.delivered,
      ),
      const ChatConversation(
        id: 'conv-5',
        contactId: 'usr-dev-4',
        name: 'Dev 4 (QuantDrive & Storage)',
        avatarInitials: 'D4',
        avatarColor: QuantColors.sunsetGold,
        lastMessage: 'Chunked multipart upload for 4K media reels synced.',
        lastMessageTime: '10:15',
        unreadCount: 0,
        isOnline: false,
        isTyping: false,
        isPinned: false,
        lastSeenText: 'Last seen 10:20 AM',
        lastMessageStatus: MessageDeliveryStatus.read,
      ),
      const ChatConversation(
        id: 'conv-6',
        contactId: 'usr-dev-6',
        name: 'Dev 6 (CodeHub & Git Engine)',
        avatarInitials: 'D6',
        avatarColor: QuantColors.crimsonRed,
        lastMessage: 'Smart HTTP packfile streaming benchmarked at 1.8GB/s.',
        lastMessageTime: 'Yesterday',
        unreadCount: 0,
        isOnline: false,
        isTyping: false,
        isPinned: false,
        lastSeenText: 'Last seen yesterday',
        lastMessageStatus: MessageDeliveryStatus.read,
      ),
    ];
  }

  static List<ChatMessage> getInitialMessages(String conversationId) {
    return [
      const ChatMessage(
        id: 'msg-1',
        conversationId: 'conv-1',
        senderId: 'usr-astra',
        senderName: 'CEO Astra',
        text: 'Initiating Wave 77 Sovereign Mobile deployment for QuantChat standalone.',
        timestamp: '12:35',
        isOutgoing: false,
        deliveryStatus: MessageDeliveryStatus.read,
        type: MessageType.text,
      ),
      const ChatMessage(
        id: 'msg-2',
        conversationId: 'conv-1',
        senderId: 'usr-me',
        senderName: 'You',
        text: 'Architecture spec received. Implementing zero-Skia clipPath, 120Hz Impeller cards, WebRTC bridge, and Chatter live stage.',
        timestamp: '12:37',
        isOutgoing: true,
        deliveryStatus: MessageDeliveryStatus.read,
        type: MessageType.text,
      ),
      const ChatMessage(
        id: 'msg-3',
        conversationId: 'conv-1',
        senderId: 'usr-astra',
        senderName: 'CEO Astra',
        text: 'Encrypted voice briefing for the WebRTC signaling gateway and peer discovery:',
        timestamp: '12:40',
        isOutgoing: false,
        deliveryStatus: MessageDeliveryStatus.read,
        type: MessageType.audio,
        audioDurationSeconds: 42,
        audioWaveform: [
          0.3, 0.6, 0.9, 0.4, 0.7, 0.8, 0.5, 0.9,
          0.6, 0.3, 0.7, 0.9, 0.8, 0.4, 0.6, 0.5,
          0.7, 0.9, 0.8, 0.4, 0.3, 0.6, 0.8, 0.5,
          0.9, 0.7, 0.4, 0.6, 0.8, 0.3, 0.5, 0.7,
        ],
      ),
      const ChatMessage(
        id: 'msg-4',
        conversationId: 'conv-1',
        senderId: 'usr-me',
        senderName: 'You',
        text: 'Acknowledged. Audio note decrypted via local hardware key. Telemetry verified at <18ms E2EE latency.',
        timestamp: '12:42',
        isOutgoing: true,
        deliveryStatus: MessageDeliveryStatus.read,
        type: MessageType.text,
      ),
      const ChatMessage(
        id: 'msg-5',
        conversationId: 'conv-1',
        senderId: 'usr-astra',
        senderName: 'CEO Astra',
        text: 'All 8 Notion agents dispatched. Tripartite Swarm operational.',
        timestamp: '12:44',
        isOutgoing: false,
        deliveryStatus: MessageDeliveryStatus.read,
        type: MessageType.text,
      ),
    ];
  }

  static AudioSpaceRoom getInitialSpaceRoom() {
    return const AudioSpaceRoom(
      id: 'space-sovereign-stage',
      title: 'Sovereign Audio Stage: 120Hz Impeller & WebRTC Mesh',
      topic: 'Building the next-gen zero-cloud E2EE communication platform',
      listenersCount: 148,
      speakersCount: 4,
      isLive: true,
      host: SpaceParticipant(
        id: 'p-host',
        name: 'CEO Astra',
        avatarInitials: 'AS',
        role: SpaceParticipantRole.host,
        isMuted: false,
        isSpeaking: true,
        accentColor: QuantColors.moltenOrange,
      ),
      speakers: [
        SpaceParticipant(
          id: 'p-spk-1',
          name: 'Node B (OS Lead)',
          avatarInitials: 'NB',
          role: SpaceParticipantRole.speaker,
          isMuted: false,
          isSpeaking: false,
          accentColor: QuantColors.sovereignCyan,
        ),
        SpaceParticipant(
          id: 'p-spk-2',
          name: 'Node C (Dev-Worker)',
          avatarInitials: 'NC',
          role: SpaceParticipantRole.speaker,
          isMuted: true,
          isSpeaking: false,
          accentColor: QuantColors.obsidianPurple,
        ),
        SpaceParticipant(
          id: 'p-spk-3',
          name: 'Dev 1 (Security)',
          avatarInitials: 'D1',
          role: SpaceParticipantRole.speaker,
          isMuted: false,
          isSpeaking: true,
          accentColor: QuantColors.emeraldMatrix,
        ),
      ],
      listeners: [
        SpaceParticipant(
          id: 'p-lis-1',
          name: 'Sarah Chen (Dev 3)',
          avatarInitials: 'SC',
          role: SpaceParticipantRole.listener,
          isHandRaised: true,
          accentColor: QuantColors.sunsetGold,
        ),
        SpaceParticipant(
          id: 'p-lis-2',
          name: 'Alex Rivera (Dev 4)',
          avatarInitials: 'AR',
          role: SpaceParticipantRole.listener,
          isHandRaised: false,
          accentColor: QuantColors.sovereignCyan,
        ),
        SpaceParticipant(
          id: 'p-lis-3',
          name: 'Marcus Vance',
          avatarInitials: 'MV',
          role: SpaceParticipantRole.listener,
          isHandRaised: false,
          accentColor: QuantColors.darkSlateSurface,
        ),
        SpaceParticipant(
          id: 'p-lis-4',
          name: 'Elena Rostova',
          avatarInitials: 'ER',
          role: SpaceParticipantRole.listener,
          isHandRaised: true,
          accentColor: QuantColors.moltenOrange,
        ),
        SpaceParticipant(
          id: 'p-lis-5',
          name: 'Dev 6 (CodeHub)',
          avatarInitials: 'D6',
          role: SpaceParticipantRole.listener,
          isHandRaised: false,
          accentColor: QuantColors.crimsonRed,
        ),
        SpaceParticipant(
          id: 'p-lis-6',
          name: 'Kavita Rao',
          avatarInitials: 'KR',
          role: SpaceParticipantRole.listener,
          isHandRaised: false,
          accentColor: QuantColors.emeraldMatrix,
        ),
      ],
    );
  }

  static List<CallHistoryItem> getInitialCallHistory() {
    return const [
      CallHistoryItem(
        id: 'call-1',
        contactName: 'CEO Astra',
        contactInitials: 'AS',
        contactAvatarColor: QuantColors.moltenOrange,
        callType: QuantCallType.video,
        isIncoming: true,
        isMissed: false,
        timestamp: 'Today, 12:15 PM',
        duration: '14m 32s',
        latencyMs: 16,
      ),
      CallHistoryItem(
        id: 'call-2',
        contactName: 'Node B (Agent OS)',
        contactInitials: 'NB',
        contactAvatarColor: QuantColors.sovereignCyan,
        callType: QuantCallType.audio,
        isIncoming: false,
        isMissed: false,
        timestamp: 'Today, 10:45 AM',
        duration: '06m 19s',
        latencyMs: 14,
      ),
      CallHistoryItem(
        id: 'call-3',
        contactName: 'Dev 1 (Auth & Security)',
        contactInitials: 'D1',
        contactAvatarColor: QuantColors.emeraldMatrix,
        callType: QuantCallType.audio,
        isIncoming: true,
        isMissed: true,
        timestamp: 'Yesterday, 05:20 PM',
        duration: 'Missed',
        latencyMs: 0,
      ),
      CallHistoryItem(
        id: 'call-4',
        contactName: 'Node C (Dev-Worker)',
        contactInitials: 'NC',
        contactAvatarColor: QuantColors.obsidianPurple,
        callType: QuantCallType.video,
        isIncoming: false,
        isMissed: false,
        timestamp: 'Yesterday, 03:10 PM',
        duration: '28m 45s',
        latencyMs: 19,
      ),
    ];
  }
}
