// Sovereign Quant Ecosystem - QuantChat Mock Repository & Initial State
// Strictly ZERO raw Unicode emojis throughout this file.
// Strictly ZERO Skia clipPath calls (120Hz Impeller & Skia acceleration).

import 'package:flutter/material.dart';
import 'package:quant_core/quant_core.dart';
import 'package:quant_theme/quant_theme.dart';
import '../models/chat_models.dart';

class ChatMockData {
  ChatMockData._();

  static List<ChatConversation> getInitialConversations() {
    return [
      const ChatConversation(
        id: 'conv-1',
        contactId: 'usr-astra',
        name: 'CEO Astra (Notion AI Swarm)',
        avatarInitials: 'AS',
        avatarColor: QuantColors.moltenOrange,
        lastMessage: 'All 8 Notion agents dispatched. Tripartite Swarm operational.',
        lastMessageTime: '12:44',
        unreadCount: 3,
        isOnline: true,
        isTyping: true,
        isPinned: true,
        lastSeenText: 'Active in Swarm Control',
        lastMessageStatus: MessageDeliveryStatus.read,
      ),
      const ChatConversation(
        id: 'conv-2',
        contactId: 'usr-node-b',
        name: 'Node B (ChatGPT Agent OS Lead)',
        avatarInitials: 'NB',
        avatarColor: QuantColors.sovereignCyan,
        lastMessage: 'Track 2 live: Voice Orb 3D canvas and dynamic tool calling green.',
        lastMessageTime: '12:38',
        unreadCount: 1,
        isOnline: true,
        isTyping: false,
        isPinned: true,
        lastSeenText: 'Online (Node B Active)',
        lastMessageStatus: MessageDeliveryStatus.read,
      ),
      const ChatConversation(
        id: 'conv-3',
        contactId: 'usr-node-c',
        name: 'Node C (CLI Dev-Worker agy.exe)',
        avatarInitials: 'NC',
        avatarColor: QuantColors.obsidianPurple,
        lastMessage: 'PR #298 merged. Staging cluster running 20 pods smoothly.',
        lastMessageTime: '12:25',
        unreadCount: 0,
        isOnline: true,
        isTyping: false,
        isPinned: true,
        lastSeenText: 'Online (<12ms Staging)',
        lastMessageStatus: MessageDeliveryStatus.read,
      ),
      const ChatConversation(
        id: 'conv-4',
        contactId: 'usr-dev-1',
        name: 'Dev 1 (Auth & Security)',
        avatarInitials: 'D1',
        avatarColor: QuantColors.emeraldMatrix,
        lastMessage: 'Hardware Keystore signed prekey bundle validated successfully.',
        lastMessageTime: '11:52',
        unreadCount: 0,
        isOnline: true,
        isTyping: false,
        isPinned: false,
        lastSeenText: 'Online',
        lastMessageStatus: MessageDeliveryStatus.delivered,
      ),
      const ChatConversation(
        id: 'conv-5',
        contactId: 'usr-dev-4',
        name: 'Dev 4 (QuantDrive & Storage)',
        avatarInitials: 'D4',
        avatarColor: QuantColors.sunsetGold,
        lastMessage: 'Chunked multipart upload for 4K media reels synced.',
        lastMessageTime: '10:15',
        unreadCount: 0,
        isOnline: false,
        isTyping: false,
        isPinned: false,
        lastSeenText: 'Last seen 10:20 AM',
        lastMessageStatus: MessageDeliveryStatus.read,
      ),
      const ChatConversation(
        id: 'conv-6',
        contactId: 'usr-dev-6',
        name: 'Dev 6 (CodeHub & Git Engine)',
        avatarInitials: 'D6',
        avatarColor: QuantColors.crimsonRed,
        lastMessage: 'Smart HTTP packfile streaming benchmarked at 1.8GB/s.',
        lastMessageTime: 'Yesterday',
        unreadCount: 0,
        isOnline: false,
        isTyping: false,
        isPinned: false,
        lastSeenText: 'Last seen yesterday',
        lastMessageStatus: MessageDeliveryStatus.delivered,
      ),
      const ChatConversation(
        id: 'conv-7',
        contactId: 'usr-dev-7',
        name: 'Dev 7 (QuantAI & ONNX)',
        avatarInitials: 'D7',
        avatarColor: QuantColors.sovereignCyan,
        lastMessage: 'Local ONNX embedding models loaded in 42ms.',
        lastMessageTime: 'Wednesday',
        unreadCount: 0,
        isOnline: false,
        isTyping: false,
        isPinned: false,
        lastSeenText: 'Offline',
        lastMessageStatus: MessageDeliveryStatus.sent,
      ),
    ];
  }

  static List<ChatMessage> getInitialMessages(String conversationId) {
    return [
      const ChatMessage(
        id: 'msg-1',
        conversationId: 'conv-1',
        senderId: 'usr-astra',
        senderName: 'CEO Astra',
        text: 'Initiating Sovereign Tripartite Swarm sync. All agent nodes report status.',
        timestamp: '12:35',
        isOutgoing: false,
        deliveryStatus: MessageDeliveryStatus.read,
        type: MessageType.text,
      ),
      const ChatMessage(
        id: 'msg-2',
        conversationId: 'conv-1',
        senderId: 'usr-me',
        senderName: 'You',
        text: 'Architecture spec received. Implementing zero-Skia clipPath, 120Hz Impeller cards, WebRTC bridge, and Chatter live stage.',
        timestamp: '12:37',
        isOutgoing: true,
        deliveryStatus: MessageDeliveryStatus.read,
        type: MessageType.text,
      ),
      const ChatMessage(
        id: 'msg-3',
        conversationId: 'conv-1',
        senderId: 'usr-astra',
        senderName: 'CEO Astra',
        text: 'Encrypted voice briefing for the WebRTC signaling gateway and peer discovery:',
        timestamp: '12:40',
        isOutgoing: false,
        deliveryStatus: MessageDeliveryStatus.read,
        type: MessageType.audio,
        audioDurationSeconds: 42,
        audioWaveform: [
          0.3, 0.6, 0.9, 0.4, 0.7, 0.8, 0.5, 0.9,
          0.6, 0.3, 0.7, 0.9, 0.8, 0.4, 0.6, 0.5,
          0.7, 0.9, 0.8, 0.4, 0.3, 0.6, 0.8, 0.5,
          0.9, 0.7, 0.4, 0.6, 0.8, 0.3, 0.5, 0.7,
        ],
      ),
      const ChatMessage(
        id: 'msg-4',
        conversationId: 'conv-1',
        senderId: 'usr-me',
        senderName: 'You',
        text: 'Acknowledged. Audio note decrypted via local hardware key. Telemetry verified at <18ms E2EE latency.',
        timestamp: '12:42',
        isOutgoing: true,
        deliveryStatus: MessageDeliveryStatus.read,
        type: MessageType.text,
      ),
      // Ephemeral message actively counting down
      const ChatMessage(
        id: 'msg-ephemeral-active',
        conversationId: 'conv-1',
        senderId: 'usr-me',
        senderName: 'You',
        text: 'Self-destructing ephemeral credentials for Staging Vault cluster access.',
        timestamp: '12:43',
        isOutgoing: true,
        deliveryStatus: MessageDeliveryStatus.delivered,
        type: MessageType.text,
        isDisappearing: true,
        disappearingDurationSeconds: 30,
        secondsRemaining: 18,
        isServerDestroyed: false,
        serverDestructionCode: 410,
      ),
      // Expired message demonstrating HTTP 410 Server Destruction
      const ChatMessage(
        id: 'msg-ephemeral-destroyed',
        conversationId: 'conv-1',
        senderId: 'usr-astra',
        senderName: 'CEO Astra',
        text: 'HTTP 410 GONE · Server Destroyed & Purged from Sovereign Mesh',
        timestamp: '12:41',
        isOutgoing: false,
        deliveryStatus: MessageDeliveryStatus.read,
        type: MessageType.text,
        isDisappearing: true,
        disappearingDurationSeconds: 30,
        secondsRemaining: 0,
        isServerDestroyed: true,
        serverDestructionCode: 410,
      ),
      const ChatMessage(
        id: 'msg-5',
        conversationId: 'conv-1',
        senderId: 'usr-astra',
        senderName: 'CEO Astra',
        text: 'All 8 Notion agents dispatched. Tripartite Swarm operational.',
        timestamp: '12:44',
        isOutgoing: false,
        deliveryStatus: MessageDeliveryStatus.read,
        type: MessageType.text,
      ),
    ];
  }

  static List<CallParticipant> getInitialCallParticipants() {
    return const [
      CallParticipant(
        id: 'part-remote-1',
        name: 'CEO Astra',
        avatarInitials: 'AS',
        avatarColor: QuantColors.moltenOrange,
        isAudioMuted: false,
        isVideoEnabled: true,
        isSpeaking: true,
        isScreenSharing: false,
        latencyMs: 14,
        videoResolution: '1080p60',
        frameRateFps: 60,
      ),
      CallParticipant(
        id: 'part-remote-2',
        name: 'Node B (OS Lead)',
        avatarInitials: 'NB',
        avatarColor: QuantColors.sovereignCyan,
        isAudioMuted: false,
        isVideoEnabled: true,
        isSpeaking: false,
        isScreenSharing: false,
        latencyMs: 18,
        videoResolution: '1080p60',
        frameRateFps: 60,
      ),
      CallParticipant(
        id: 'part-remote-3',
        name: 'Node C (Dev-Worker)',
        avatarInitials: 'NC',
        avatarColor: QuantColors.obsidianPurple,
        isAudioMuted: true,
        isVideoEnabled: true,
        isSpeaking: false,
        isScreenSharing: false,
        latencyMs: 12,
        videoResolution: '1080p60',
        frameRateFps: 60,
      ),
      CallParticipant(
        id: 'part-local-me',
        name: 'You (Local Impeller)',
        avatarInitials: 'ME',
        avatarColor: QuantColors.moltenOrange,
        isAudioMuted: false,
        isVideoEnabled: true,
        isSpeaking: false,
        isScreenSharing: false,
        latencyMs: 0,
        videoResolution: '1080p60',
        frameRateFps: 60,
      ),
    ];
  }

  static AudioSpaceRoom getInitialSpaceRoom() {
    return const AudioSpaceRoom(
      id: 'space-sovereign-stage',
      title: 'Sovereign Audio Stage: 120Hz Impeller & WebRTC Mesh',
      topic: 'Building the next-gen zero-cloud E2EE communication platform',
      listenersCount: 148,
      speakersCount: 4,
      isLive: true,
      host: SpaceParticipant(
        id: 'p-host',
        name: 'CEO Astra',
        avatarInitials: 'AS',
        role: SpaceParticipantRole.host,
        isMuted: false,
        isSpeaking: true,
        accentColor: QuantColors.moltenOrange,
      ),
      speakers: [
        SpaceParticipant(
          id: 'p-spk-1',
          name: 'Node B (OS Lead)',
          avatarInitials: 'NB',
          role: SpaceParticipantRole.speaker,
          isMuted: false,
          isSpeaking: false,
          accentColor: QuantColors.sovereignCyan,
        ),
        SpaceParticipant(
          id: 'p-spk-2',
          name: 'Node C (Dev-Worker)',
          avatarInitials: 'NC',
          role: SpaceParticipantRole.speaker,
          isMuted: true,
          isSpeaking: false,
          accentColor: QuantColors.obsidianPurple,
        ),
        SpaceParticipant(
          id: 'p-spk-3',
          name: 'Dev 1 (Security)',
          avatarInitials: 'D1',
          role: SpaceParticipantRole.speaker,
          isMuted: false,
          isSpeaking: true,
          accentColor: QuantColors.emeraldMatrix,
        ),
      ],
      listeners: [
        SpaceParticipant(
          id: 'p-lis-1',
          name: 'Sarah Chen (Dev 3)',
          avatarInitials: 'SC',
          role: SpaceParticipantRole.listener,
          isHandRaised: true,
          accentColor: QuantColors.sunsetGold,
        ),
        SpaceParticipant(
          id: 'p-lis-2',
          name: 'Alex Rivera (Dev 4)',
          avatarInitials: 'AR',
          role: SpaceParticipantRole.listener,
          isHandRaised: false,
          accentColor: QuantColors.sovereignCyan,
        ),
        SpaceParticipant(
          id: 'p-lis-3',
          name: 'Marcus Vance',
          avatarInitials: 'MV',
          role: SpaceParticipantRole.listener,
          isHandRaised: false,
          accentColor: QuantColors.darkSlateSurface,
        ),
        SpaceParticipant(
          id: 'p-lis-4',
          name: 'Elena Rostova',
          avatarInitials: 'ER',
          role: SpaceParticipantRole.listener,
          isHandRaised: true,
          accentColor: QuantColors.moltenOrange,
        ),
        SpaceParticipant(
          id: 'p-lis-5',
          name: 'Dev 6 (CodeHub)',
          avatarInitials: 'D6',
          role: SpaceParticipantRole.listener,
          isHandRaised: false,
          accentColor: QuantColors.crimsonRed,
        ),
        SpaceParticipant(
          id: 'p-lis-6',
          name: 'Kavita Rao',
          avatarInitials: 'KR',
          role: SpaceParticipantRole.listener,
          isHandRaised: false,
          accentColor: QuantColors.emeraldMatrix,
        ),
      ],
    );
  }

  static List<CallHistoryItem> getInitialCallHistory() {
    return const [
      CallHistoryItem(
        id: 'call-1',
        contactName: 'CEO Astra',
        contactInitials: 'AS',
        contactAvatarColor: QuantColors.moltenOrange,
        callType: QuantCallType.video,
        isIncoming: true,
        isMissed: false,
        timestamp: 'Today, 12:15 PM',
        duration: '14m 32s',
        latencyMs: 16,
      ),
      CallHistoryItem(
        id: 'call-2',
        contactName: 'Node B (Agent OS)',
        contactInitials: 'NB',
        contactAvatarColor: QuantColors.sovereignCyan,
        callType: QuantCallType.audio,
        isIncoming: false,
        isMissed: false,
        timestamp: 'Today, 10:45 AM',
        duration: '06m 19s',
        latencyMs: 14,
      ),
      CallHistoryItem(
        id: 'call-3',
        contactName: 'Dev 1 (Auth & Security)',
        contactInitials: 'D1',
        contactAvatarColor: QuantColors.emeraldMatrix,
        callType: QuantCallType.audio,
        isIncoming: true,
        isMissed: true,
        timestamp: 'Yesterday, 05:20 PM',
        duration: 'Missed',
        latencyMs: 0,
      ),
      CallHistoryItem(
        id: 'call-4',
        contactName: 'Node C (Dev-Worker)',
        contactInitials: 'NC',
        contactAvatarColor: QuantColors.obsidianPurple,
        callType: QuantCallType.video,
        isIncoming: false,
        isMissed: false,
        timestamp: 'Yesterday, 03:10 PM',
        duration: '28m 45s',
        latencyMs: 19,
      ),
    ];
  }

  static List<ChatGroupMember> getInitialGroupMembers() {
    return const [
      ChatGroupMember(
        id: 'usr-astra',
        name: 'CEO Astra (Notion AI Swarm)',
        avatarInitials: 'AS',
        avatarColor: QuantColors.moltenOrange,
        isAdmin: true,
        isCreator: true,
        phoneOrHandle: '@astra.ceo',
        isOnline: true,
      ),
      ChatGroupMember(
        id: 'usr-node-b',
        name: 'Node B (ChatGPT Agent OS Lead)',
        avatarInitials: 'NB',
        avatarColor: QuantColors.sovereignCyan,
        isAdmin: true,
        isCreator: false,
        phoneOrHandle: '@node.b',
        isOnline: true,
      ),
      ChatGroupMember(
        id: 'usr-node-c',
        name: 'Node C (CLI Dev-Worker agy.exe)',
        avatarInitials: 'NC',
        avatarColor: QuantColors.obsidianPurple,
        isAdmin: false,
        isCreator: false,
        phoneOrHandle: '@node.c',
        isOnline: true,
      ),
      ChatGroupMember(
        id: 'usr-dev-1',
        name: 'Dev 1 (Auth & Security)',
        avatarInitials: 'D1',
        avatarColor: QuantColors.emeraldMatrix,
        isAdmin: false,
        isCreator: false,
        phoneOrHandle: '@dev1.auth',
        isOnline: false,
      ),
      ChatGroupMember(
        id: 'usr-dev-4',
        name: 'Dev 4 (QuantDrive & Storage)',
        avatarInitials: 'D4',
        avatarColor: QuantColors.sunsetGold,
        isAdmin: false,
        isCreator: false,
        phoneOrHandle: '@dev4.storage',
        isOnline: false,
      ),
      ChatGroupMember(
        id: 'usr-dev-6',
        name: 'Dev 6 (CodeHub & Git Engine)',
        avatarInitials: 'D6',
        avatarColor: QuantColors.crimsonRed,
        isAdmin: false,
        isCreator: false,
        phoneOrHandle: '@dev6.git',
        isOnline: false,
      ),
      ChatGroupMember(
        id: 'usr-dev-7',
        name: 'Dev 7 (QuantAI & ONNX)',
        avatarInitials: 'D7',
        avatarColor: QuantColors.sovereignCyan,
        isAdmin: false,
        isCreator: false,
        phoneOrHandle: '@dev7.onnx',
        isOnline: true,
      ),
    ];
  }

  static List<ChatMediaItem> getInitialMediaItems() {
    return const [
      ChatMediaItem(
        id: 'med-1',
        title: 'Cluster Topology Diagram.png',
        subtitle: '1080p · 2.4 MB · FastCDC Dedup 3.4x',
        category: ChatMediaCategory.media,
        timestamp: '12:40 PM',
        fileSizeBytes: 2457600,
        iconData: Icons.image_rounded,
        accentColor: QuantColors.sovereignCyan,
      ),
      ChatMediaItem(
        id: 'med-2',
        title: 'Impeller 120Hz Benchmarks.mp4',
        subtitle: '60fps · 14.8 MB · VP9 Encrypted',
        category: ChatMediaCategory.media,
        timestamp: 'Yesterday',
        fileSizeBytes: 15518924,
        iconData: Icons.play_circle_fill_rounded,
        accentColor: QuantColors.moltenOrange,
      ),
      ChatMediaItem(
        id: 'doc-1',
        title: 'E2EE_Signal_Protocol_Spec_v3.pdf',
        subtitle: 'PDF Document · 842 KB · Verified SHA-256',
        category: ChatMediaCategory.document,
        timestamp: 'Today, 11:20 AM',
        fileSizeBytes: 862208,
        iconData: Icons.picture_as_pdf_rounded,
        accentColor: QuantColors.crimsonRed,
      ),
      ChatMediaItem(
        id: 'doc-2',
        title: 'FastCDC_Chunk_Index_Manifest.json',
        subtitle: 'JSON Data · 128 KB · 64 Chunks',
        category: ChatMediaCategory.document,
        timestamp: 'Yesterday',
        fileSizeBytes: 131072,
        iconData: Icons.data_object_rounded,
        accentColor: QuantColors.emeraldMatrix,
      ),
      ChatMediaItem(
        id: 'link-1',
        title: 'Quant Ecosystem Staging Gateway',
        subtitle: 'https://staging.quantchat.in/mesh/status',
        category: ChatMediaCategory.link,
        timestamp: 'Today, 09:15 AM',
        url: 'https://staging.quantchat.in/mesh/status',
        iconData: Icons.link_rounded,
        accentColor: QuantColors.sovereignCyan,
      ),
      ChatMediaItem(
        id: 'link-2',
        title: 'WebRTC Mesh Architecture RFC',
        subtitle: 'https://quant.org/rfcs/webrtc-mesh-v2',
        category: ChatMediaCategory.link,
        timestamp: '2 days ago',
        url: 'https://quant.org/rfcs/webrtc-mesh-v2',
        iconData: Icons.public_rounded,
        accentColor: QuantColors.obsidianPurple,
      ),
    ];
  }
}
