// ============================================================================
// Security Package - Container Security Scanner
// ============================================================================

import type { ContainerValidation, ContainerIssue, TrivyScanResult } from '../types';

/** Rules for Dockerfile validation */
const DOCKERFILE_RULES = [
  {
    id: 'CS001',
    rule: 'no-root-user',
    pattern: /^USER\s+(?!root)/m,
    inverse: true,
    severity: 'critical' as const,
    description: 'Container runs as root user',
    remediation: 'Add USER directive with non-root user (e.g., USER 65532)',
  },
  {
    id: 'CS002',
    rule: 'no-secrets',
    pattern: /(?:ENV|ARG)\s+(?:.*(?:PASSWORD|SECRET|TOKEN|KEY|PRIVATE).*=\S+)/i,
    inverse: false,
    severity: 'critical' as const,
    description: 'Secrets found in Dockerfile environment variables',
    remediation:
      'Use runtime secrets injection (Docker secrets, Vault) instead of build-time ENV/ARG',
  },
  {
    id: 'CS003',
    rule: 'use-specific-tag',
    pattern: /^FROM\s+\S+:latest/m,
    inverse: false,
    severity: 'medium' as const,
    description: 'Using :latest tag for base image',
    remediation: 'Pin base image to a specific version/digest for reproducibility',
  },
  {
    id: 'CS004',
    rule: 'no-add',
    pattern: /^ADD\s+(?!https?:\/\/)/m,
    inverse: false,
    severity: 'low' as const,
    description: 'Using ADD instead of COPY for local files',
    remediation: 'Use COPY for local files; ADD auto-extracts archives which is unexpected',
  },
  {
    id: 'CS005',
    rule: 'no-curl-pipe',
    pattern: /curl.*\|\s*(?:bash|sh)/,
    inverse: false,
    severity: 'high' as const,
    description: 'Piping curl output to shell',
    remediation: 'Download files first, verify checksums, then execute',
  },
  {
    id: 'CS006',
    rule: 'healthcheck',
    pattern: /^HEALTHCHECK/m,
    inverse: true,
    severity: 'low' as const,
    description: 'No HEALTHCHECK instruction defined',
    remediation: 'Add HEALTHCHECK to enable container orchestrator health monitoring',
  },
];

/**
 * ContainerSecurityScanner - Validates Dockerfiles and container configurations.
 * Checks for security best practices: non-root, distroless, no secrets, minimal layers.
 */
export class ContainerSecurityScanner {
  /** Validate a Dockerfile content for security issues */
  validateDockerfile(content: string): ContainerValidation {
    const issues: ContainerIssue[] = [];

    for (const rule of DOCKERFILE_RULES) {
      const matches = rule.pattern.test(content);
      const hasIssue = rule.inverse ? !matches : matches;

      if (hasIssue) {
        // For inverse rules, find the relevant line
        let line: number | undefined;
        if (!rule.inverse) {
          const lines = content.split('\n');
          for (let i = 0; i < lines.length; i++) {
            if (rule.pattern.test(lines[i]!)) {
              line = i + 1;
              break;
            }
          }
        }

        issues.push({
          severity: rule.severity,
          rule: rule.rule,
          description: rule.description,
          line,
          remediation: rule.remediation,
        });
      }
    }

    // Check for multi-stage build
    const fromCount = (content.match(/^FROM\s/gm) || []).length;
    if (fromCount < 2) {
      issues.push({
        severity: 'medium',
        rule: 'multi-stage',
        description: 'Not using multi-stage build',
        remediation: 'Use multi-stage builds to reduce final image size and attack surface',
      });
    }

    const score = this.calculateScore(issues);
    return { valid: issues.filter((i) => i.severity === 'critical').length === 0, issues, score };
  }

  /** Generate a secure Dockerfile for a service */
  generateSecureDockerfile(service: string, baseImage: string = 'node:22-slim'): string {
    return `# Secure Dockerfile for ${service}
# Generated by ContainerSecurityScanner

# Stage 1: Build
FROM ${baseImage} AS builder

WORKDIR /app

# Copy package files for dependency caching
COPY package.json pnpm-lock.yaml ./
RUN corepack enable && pnpm install --frozen-lockfile --prod=false

# Copy source and build
COPY src/ ./src/
COPY tsconfig.json ./
RUN pnpm build

# Stage 2: Production (distroless)
FROM gcr.io/distroless/nodejs22-debian12 AS production

# Set non-root user
USER 65532:65532

WORKDIR /app

# Copy only production artifacts
COPY --from=builder --chown=65532:65532 /app/dist ./dist
COPY --from=builder --chown=65532:65532 /app/node_modules ./node_modules
COPY --from=builder --chown=65532:65532 /app/package.json ./

# Read-only filesystem
# (enforced via container runtime security context)

# No shell available in distroless

ENV NODE_ENV=production

EXPOSE 3000

CMD ["dist/index.js"]
`;
  }

  /** Process Trivy scan results (interface for integration) */
  scanImage(imageRef: string, trivyOutput?: TrivyScanResult): TrivyScanResult {
    if (trivyOutput) {
      return trivyOutput;
    }

    // Return empty placeholder when no Trivy output provided
    return {
      imageRef,
      vulnerabilities: [],
      scanTime: Date.now(),
    };
  }

  private calculateScore(issues: ContainerIssue[]): number {
    let score = 100;
    for (const issue of issues) {
      switch (issue.severity) {
        case 'critical':
          score -= 25;
          break;
        case 'high':
          score -= 15;
          break;
        case 'medium':
          score -= 10;
          break;
        case 'low':
          score -= 5;
          break;
      }
    }
    return Math.max(0, score);
  }
}
