import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { UniversalSSOTokenBridge } from '@quant/shared-ui';
import { getAuthToken, setAuthToken, clearAuthSession } from '../lib/auth';
import {
  ingestSSOToken,
  getAccessToken,
  clearAccessToken,
  authSession,
} from '../services/auth-session';

describe('QuantAI SSO Token Handoff & Session Ingestion', () => {
  beforeEach(() => {
    localStorage.clear();
    clearAccessToken();
    clearAuthSession();
    vi.restoreAllMocks();
  });

  afterEach(() => {
    localStorage.clear();
    clearAccessToken();
    clearAuthSession();
  });

  it('reads auth token from quant_access_token and quant_auth_token in localStorage', () => {
    expect(getAuthToken()).toBeNull();

    localStorage.setItem('quant_access_token', 'jwt-quantai-access-111');
    expect(getAuthToken()).toBe('jwt-quantai-access-111');

    clearAuthSession();
    expect(getAuthToken()).toBeNull();

    localStorage.setItem('quant_auth_token', 'jwt-quantai-auth-222');
    expect(getAuthToken()).toBe('jwt-quantai-auth-222');
  });

  it('sets token across all ecosystem storage keys and writes cookie', () => {
    const testToken = 'jwt-ai-token-333';
    setAuthToken(testToken, {
      id: 'usr_1',
      email: 'member@quantmail.in',
      name: 'Quant Member',
      plan: 'pro',
    });

    expect(localStorage.getItem('quant_access_token')).toBe(testToken);
    expect(localStorage.getItem('quant_auth_token')).toBe(testToken);
    expect(localStorage.getItem('token')).toBe(testToken);
    expect(localStorage.getItem('quant_token')).toBe(testToken);
    expect(document.cookie).toContain('quant_access_token=');
  });

  it('ingestSSOToken updates in-memory token and persists to storage', () => {
    const ssoToken = 'jwt-sso-ingested-444';
    ingestSSOToken(ssoToken);

    expect(getAccessToken()).toBe(ssoToken);
    expect(getAuthToken()).toBe(ssoToken);
    expect(localStorage.getItem('quant_access_token')).toBe(ssoToken);
  });

  it('ingests __quant_sso_ticket generated by UniversalSSOTokenBridge for QuantAI', () => {
    const bridge = UniversalSSOTokenBridge.getInstance();

    bridge.setCurrentSession(
      {
        userId: 'user-ai-sso-2',
        email: 'ai-tester@quantmail.in',
        displayName: 'AI Tester',
        token: 'jwt-ai-sso-token-555',
        currentApp: 'quantai',
      },
      3600,
    );

    const ticket = bridge.generateHandoffTicket('quantai');
    expect(ticket).toBeTruthy();

    const verified = bridge.verifyHandoffTicket(ticket!);
    expect(verified).not.toBeNull();
    expect(verified?.userId).toBe('user-ai-sso-2');
    expect(verified?.token).toBe('jwt-ai-sso-token-555');

    // Ingest into quantai
    ingestSSOToken(verified!.token!);
    expect(getAccessToken()).toBe('jwt-ai-sso-token-555');
    expect(localStorage.getItem('quant_access_token')).toBe('jwt-ai-sso-token-555');
  });

  it('authSession.refresh falls back to stored SSO token when /auth/refresh returns 401/network', async () => {
    localStorage.setItem('quant_access_token', 'jwt-cached-sso-666');

    // Stub global fetch with a rejection
    vi.stubGlobal('fetch', vi.fn().mockRejectedValue(new Error('Network error')));

    const result = await authSession.refresh();
    expect(result.success).toBe(true);
    expect(result.data?.accessToken).toBe('jwt-cached-sso-666');
    expect(getAccessToken()).toBe('jwt-cached-sso-666');
  });
});
