apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:latest
          env:
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: quant-secrets
                  key: meili-master-key
          ports:
            - containerPort: 7700
          volumeMounts:
            - name: meili-storage
              mountPath: /meili_data
      volumes:
        - name: meili-storage
          persistentVolumeClaim:
            claimName: meili-pvc
