'use client';

import React from 'react';
import { motion, AnimatePresence, useReducedMotion } from 'framer-motion';
import { spring } from '@quant/brand';
import { useMotionConfig } from './MotionConfig';
import { useFocusTrap } from '../../hooks/useFocusTrap';

export interface SlidePanelProps {
  isOpen: boolean;
  side?: 'left' | 'right';
  width?: string;
  onClose?: () => void;
  children: React.ReactNode;
  className?: string;
  animated?: boolean;
  /**
   * What this drawer is, for the reader who cannot see where it came from.
   *
   * The props were enumerated rather than spread and the file contained no
   * `role` and no `aria-*` at all, so a fixed full-height panel at z-index 50
   * announced as an anonymous group of content that appeared from nowhere — and
   * a consumer had no way to name it either. Defaulted rather than required
   * because a generic name still beats none; pass `aria-labelledby` instead when
   * the drawer has a heading of its own, which is always the better name.
   */
  'aria-label'?: string;
  /** The drawer's own heading. Wins over `aria-label`, so only one is emitted. */
  'aria-labelledby'?: string;
}

export function SlidePanel({
  isOpen,
  side = 'right',
  width = '320px',
  onClose,
  children,
  className,
  animated = true,
  'aria-label': ariaLabel = 'Panel',
  'aria-labelledby': ariaLabelledBy,
}: SlidePanelProps) {
  const { shouldAnimate: contextAnimate } = useMotionConfig();
  const prefersReducedMotion = useReducedMotion();
  const shouldAnimate = animated && contextAnimate && !prefersReducedMotion;

  /*
    A drawer that can be closed is a modal one, and it gets all four of the
    things its siblings in this package get: a scrim, `aria-modal`, Tab
    containment, and Escape. A drawer that cannot — no `onClose` — gets none of
    them, because a Tab trap with no exit is a prison and a scrim with nothing to
    dismiss it is a dead page. One prop the component already had decides all
    four together, so the halves can never disagree: `aria-modal="true"` claims
    everything outside is inert, and the trap and the scrim are what make that
    claim true for a keyboard and for a mouse respectively.

    The panel itself used to carry the click handler, guarded by
    `e.target === e.currentTarget` — a backdrop-click-to-close written without a
    backdrop, so clicking a gap between the drawer's own children dismissed it.
    The scrim owns dismissal now, which is what that guard was reaching for.
  */
  const dismissible = typeof onClose === 'function';
  const panelRef = useFocusTrap<HTMLDivElement>({
    active: isOpen && dismissible,
    onEscape: onClose,
  });

  const xOffset = side === 'right' ? '100%' : '-100%';

  const panelStyle: React.CSSProperties = {
    position: 'fixed',
    top: 0,
    [side]: 0,
    width,
    height: '100%',
    zIndex: 50,
  };

  // Inline, like every other style in this file: a class would have to be
  // generated by the *consumer's* Tailwind build to do anything at all.
  const scrimStyle: React.CSSProperties = {
    position: 'fixed',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    zIndex: 49,
  };

  /*
    Both render paths, one source of truth. The static branch below is a separate
    return, and an identity that only lands on the animated one is a drawer that
    loses its role and its name for every user with `prefers-reduced-motion` set.
  */
  const dialogProps = {
    className,
    style: panelStyle,
    role: 'dialog' as const,
    'aria-label': ariaLabelledBy ? undefined : ariaLabel,
    'aria-labelledby': ariaLabelledBy,
    'aria-modal': dismissible ? true : undefined,
  };

  if (!shouldAnimate) {
    if (!isOpen) return null;
    return (
      <>
        {dismissible && <div style={scrimStyle} onClick={onClose} aria-hidden="true" />}
        <div ref={panelRef} {...dialogProps}>
          {children}
        </div>
      </>
    );
  }

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          {dismissible && (
            <motion.div
              key="scrim"
              style={scrimStyle}
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={onClose}
              aria-hidden="true"
            />
          )}
          <motion.div
            key="panel"
            ref={panelRef}
            {...dialogProps}
            initial={{ x: xOffset }}
            animate={{ x: 0 }}
            exit={{ x: xOffset }}
            transition={{
              type: 'spring',
              damping: spring.stiff.damping,
              stiffness: spring.stiff.stiffness,
              mass: spring.stiff.mass,
            }}
          >
            {children}
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}
