apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-turn-credentials
  labels:
    app: coturn
type: Opaque
data:
  static-auth-secret: {{ .Values.coturn.staticAuthSecret | default (randAlphaNum 64) | b64enc | quote }}
