apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-coturn
  labels:
    app: coturn
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: turn-udp
      port: {{ .Values.coturn.listeningPort }}
      targetPort: turn-udp
      protocol: UDP
    - name: turn-tcp
      port: {{ .Values.coturn.listeningPort }}
      targetPort: turn-tcp
      protocol: TCP
    - name: turn-tls
      port: {{ .Values.coturn.tlsListeningPort }}
      targetPort: turn-tls
      protocol: TCP
  selector:
    app: coturn
