import type {QuantyToolHandler} from '@quant/quanty-contracts';
export const createProductTools=():QuantyToolHandler[]=>[
{descriptor:{toolId:'quantmail.draft.create',ownerProduct:'quantmail',version:'v1',capability:'mail.draft.create',resourceScope:['mail.message'],inputSchema:{type:'object'},outputSchema:{type:'object'},riskTier:1,confirmationPolicy:'never',timeoutMs:10000,retryPolicy:{maxAttempts:2,backoffMs:250},idempotencyPolicy:'required',verificationStrategy:'draft-readback',auditPolicy:'always'},execute:async(input,ctx)=>({accepted:true,owner:'quantmail',action:'draft.create',input,resourceRefs:ctx.resourceRefs})},
{descriptor:{toolId:'quantmail.send',ownerProduct:'quantmail',version:'v1',capability:'mail.send',resourceScope:['mail.message'],inputSchema:{type:'object'},outputSchema:{type:'object'},riskTier:3,confirmationPolicy:'conditional',timeoutMs:15000,retryPolicy:{maxAttempts:1,backoffMs:0},idempotencyPolicy:'required',verificationStrategy:'authoritative-read',auditPolicy:'always'},execute:async(input,ctx)=>({accepted:true,owner:'quantmail',action:'send',input,resourceRefs:ctx.resourceRefs})},
{descriptor:{toolId:'quantchat.message.send',ownerProduct:'quantchat',version:'v1',capability:'chat.message.send',resourceScope:['chat.message'],inputSchema:{type:'object'},outputSchema:{type:'object'},riskTier:3,confirmationPolicy:'conditional',timeoutMs:10000,retryPolicy:{maxAttempts:1,backoffMs:0},idempotencyPolicy:'required',verificationStrategy:'message-readback',auditPolicy:'always'},execute:async(input,ctx)=>({accepted:true,owner:'quantchat',action:'message.send',input,resourceRefs:ctx.resourceRefs})},
{descriptor:{toolId:'quantchat.meet.start',ownerProduct:'quantchat',version:'v1',capability:'chat.meet.start',resourceScope:['chat.meeting'],inputSchema:{type:'object'},outputSchema:{type:'object'},riskTier:3,confirmationPolicy:'conditional',timeoutMs:15000,retryPolicy:{maxAttempts:1,backoffMs:0},idempotencyPolicy:'required',verificationStrategy:'meeting-state-readback',auditPolicy:'always'},execute:async(input,ctx)=>({accepted:true,owner:'quantchat',action:'meet.start',input,resourceRefs:ctx.resourceRefs})},
{descriptor:{toolId:'quantmax.game.search',ownerProduct:'quantmax',version:'v1',capability:'game.search',resourceScope:['quantmax.game'],inputSchema:{type:'object'},outputSchema:{type:'object'},riskTier:0,confirmationPolicy:'never',timeoutMs:5000,retryPolicy:{maxAttempts:2,backoffMs:200},idempotencyPolicy:'optional',verificationStrategy:'catalog-read',auditPolicy:'minimal'},execute:async(input)=>({accepted:true,owner:'quantmax',action:'game.search',input})},
{descriptor:{toolId:'quantmax.game.launch',ownerProduct:'quantmax',version:'v1',capability:'game.launch',resourceScope:['quantmax.game','quantmax.session'],inputSchema:{type:'object'},outputSchema:{type:'object'},riskTier:2,confirmationPolicy:'conditional',timeoutMs:10000,retryPolicy:{maxAttempts:2,backoffMs:250},idempotencyPolicy:'required',verificationStrategy:'session-state-readback',auditPolicy:'always'},execute:async(input,ctx)=>({accepted:true,owner:'quantmax',action:'game.launch',input,resourceRefs:ctx.resourceRefs})},
{descriptor:{toolId:'quantmax.matchmaking.start',ownerProduct:'quantmax',version:'v1',capability:'game.matchmaking.start',resourceScope:['quantmax.matchmaking'],inputSchema:{type:'object'},outputSchema:{type:'object'},riskTier:2,confirmationPolicy:'conditional',timeoutMs:10000,retryPolicy:{maxAttempts:2,backoffMs:250},idempotencyPolicy:'required',verificationStrategy:'ticket-state-readback',auditPolicy:'always'},execute:async(input,ctx)=>({accepted:true,owner:'quantmax',action:'matchmaking.start',input,resourceRefs:ctx.resourceRefs})}
];